# Pandas

Библиотека pandas (panel datasets)

Библиотека - это набор специальных инструментов для выполнения определенных задач

**time** - для работы со временем

**pandas** - для любых операций с таблицами данных

**numpy** (numeric python) - для разного рода математических операций. Является основой для pandas

**matplotlib, seaborn** - для визуализаций

pytorch - для написания нейросетей

cv2 - для инструментов компьютерного зрения

In [1]:
# Команда import вызывает библиотеку в оперативную память
# Команда as присваивает библиотеке алиас (произвище)
import pandas as pd
import numpy as np

Основными структурами данных в Pandas являются серии и датафреймы

Серия - это набор данных одного типа с наличием названия этого набора идентификаторов каждой записи в наборе

Датафрейм - это набор серий (таблица)

## Серия (Series)

### Базовый функционал работы с сериями

In [2]:
# Создаем объект Series, состоящий из четырех целых чисел (1,2,3,4)
# Обращаемся к библиотеке pd, а далее через точку вызываем команду Series, которая (как list) создает из множества определенный тип данных
# В качестве аргумента передаем список с числами типа int
a = pd.Series([1,2,3,4])

In [3]:
a

0    1
1    2
2    3
3    4
dtype: int64

In [15]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

Атрибут - это составной элемент объекта (по принципу матрешки объект внутри другого объекта)

Некоторые из атрибутов можно менять

Вызывается атрибут, как и метод, через точку после имени объекта

Вызывая метод, мы ставим () в конце

Вызывая атрибут, скобки в конце не ставятся

Атрибуты:
1) Индекс
2) Имя серии
3) Тип данных
4) Имя индекса
5) Форма
6) Количество элементов
7) Значения

In [7]:
# Вызов индекса:
a.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
# Вызываем имя серии (название переменной)
a.name

In [9]:
# Вызываем тип данных
a.dtype

dtype('int64')

In [10]:
# Вызываем имя индекса
a.index.name

In [11]:
# Вызываем размер серии
a.shape

(4,)

In [13]:
# Вызываем количество элементов (ячеек)
a.size

4

In [14]:
# Вызываем значения серии
a.values

array([1, 2, 3, 4])

In [16]:
# Посмотрим на тип, в котором .values возвращает значения
type(a.values)

numpy.ndarray

### Работа с атрибутами серий

In [17]:
# Создадим серию с явным указанием индекса
b = pd.Series([1,2,3,4], index = ['a', 'b', 'c', 'd'])

In [18]:
b

a    1
b    2
c    3
d    4
dtype: int64

In [21]:
# Преобразуем Series в dictionary
b.to_dict()

{'a': 1, 'b': 2, 'c': 3, 'd': 4}

In [22]:
b.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [23]:
# Такую же серию с индесом можно создать из объекта dict
c = pd.Series({'a':1, 'b':2, 'c':3, 'd':4})

In [24]:
c

a    1
b    2
c    3
d    4
dtype: int64

In [25]:
c.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [26]:
# Присваиваем имя данным
c.name = 'Number'

In [27]:
c

a    1
b    2
c    3
d    4
Name: Number, dtype: int64

### Создание серии со всеми атрибутами

In [28]:
# Создаем серию с данными о ценах по 3 товарам
prices = pd.Series({'Яблоки' : 150, 'Бананы' : 120, 'Апельсины' : 200}, name = 'Цены')

In [29]:
prices

Яблоки       150
Бананы       120
Апельсины    200
Name: Цены, dtype: int64

In [30]:
prices.dtypes

dtype('int64')

In [33]:
prices.index

Index(['Яблоки', 'Бананы', 'Апельсины'], dtype='object')

In [34]:
# Назначим имя индексу
prices.index.name = 'Фрукты'

In [35]:
prices

Фрукты
Яблоки       150
Бананы       120
Апельсины    200
Name: Цены, dtype: int64

In [36]:
# Вызовем отдельно цены
prices.values

array([150, 120, 200])

In [37]:
# Проверим тип объекта
type(prices)

pandas.core.series.Series

## DataFrame (датафрейм)

Датафрейм - это таблица, у которой есть названия строк (index) и названия столбцов (columns)

In [38]:
# Создаем датафрейм из списка списков, т.е. внутрь большого списка вкладыются маленькие
df1 = pd.DataFrame([[1,2,3], [4,5,6], [7,8,9]])

In [39]:
df1

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

Атрибуты
1) Индекс
2) Названия столбцов
3) Имя индекса
4) Тип данных
5) Форма датафрейма
6) Количество элементов

In [40]:
df1.index

RangeIndex(start=0, stop=3, step=1)

In [41]:
# Cоздадим датафрейм с явным указанием имен строк (index) и столбцов (columns)
df2 = pd.DataFrame([[1,2,3], [4,5,6], [7,8,9]], index = ['a', 'b', 'c'], columns = ['x', 'y', 'z'])

In [42]:
df2

   x  y  z
a  1  2  3
b  4  5  6
c  7  8  9

In [43]:
df2.index

Index(['a', 'b', 'c'], dtype='object')

In [44]:
df2.columns

Index(['x', 'y', 'z'], dtype='object')

In [45]:
# Можно создать датафрейм из словаря, где keys - названиям столбцов, а values - списки со значениями переменной
# Создадим датафрейм с ценами на фрукты в течение 3 месяцев
prices_df = pd.DataFrame(
    {
        'Яблоки'    : [150, 160, 140],
        'Бананы'    : [120, 110, 100],
        'Апельсины' : [200, 210, 220]
    },
    index = ['Январь', 'Февраль', 'Март']
)
prices_df

         Яблоки  Бананы  Апельсины
Январь      150     120        200
Февраль     160     110        210
Март        140     100        220

In [46]:
type(prices_df)

pandas.core.frame.DataFrame

In [47]:
# Узнаем размер датафрейма (строки х столбцы)
prices_df.shape

(3, 3)

In [48]:
# Узнаем количество элементов датафрейма
prices_df.size

9

## Основные приемы работы с датафреймами и сериями

### Вызов столбцов (аналог select в SQL)

In [49]:
# Способ 1. Если из таблицы нужно вызвать определенный столбец, то его имя указывается в квадратных скобках
prices_df['Яблоки']

Январь     150
Февраль    160
Март       140
Name: Яблоки, dtype: int64

In [50]:
type(prices_df['Яблоки'])

pandas.core.series.Series

In [51]:
# Способ 2. Можно вызвать через указание назвнаия столбца после точки
# Не рекомендуется! (легко спутать с методами и атрибутами)
prices_df.Яблоки

Январь     150
Февраль    160
Март       140
Name: Яблоки, dtype: int64

In [52]:
# Если нужно вызвать несколько столбцов, они помещаются внутрь списка и список передается в dataframe в квадратных скобках
prices_df[['Яблоки', 'Апельсины']]

         Яблоки  Апельсины
Январь      150        200
Февраль     160        210
Март        140        220

In [53]:
cols = ['Яблоки', 'Апельсины'] # Можно сначала создать объект типа list из наименований нужных колонок
prices_df[cols] # Далее передать его в квадратные скобки за DataFrame, чтобы вызвать нужные столбцы

         Яблоки  Апельсины
Январь      150        200
Февраль     160        210
Март        140        220

### Метод loc (location) для выбора столбцов и строк по условию

In [54]:
# Метод loc пишется через точку после датафрейма
# В отличие от всех остальных методов (кроме iloc) его аргументы пишутся в КВАДРАТНЫХ скобках
# Первая позиция в loc - это название строки / строк (здесь можно указать логическое выражение, чтобы выбрать нужные строки)
# Вторая позиция в loc - это название столбца
prices_df.loc['Январь', 'Яблоки']

np.int64(150)

In [55]:
# Если нужно выбрать столбец целиком, то на месте строк ставится :
# Если нужно выбрать одну строку, то на месте столбцов ставится :
prices_df.loc[:, 'Яблоки']

Январь     150
Февраль    160
Март       140
Name: Яблоки, dtype: int64

In [56]:
# Можно вызвать несколько столбцов, указав их в списке
prices_df.loc[:, ['Яблоки', 'Апельсины']]

         Яблоки  Апельсины
Январь      150        200
Февраль     160        210
Март        140        220

In [57]:
# Можно вызвать отдельно строку, указав ее имя в .loc[]
prices_df.loc['Январь']

Яблоки       150
Бананы       120
Апельсины    200
Name: Январь, dtype: int64

In [58]:
# Равносильно операции выше, но с указанием : на месте столбцов
prices_df.loc['Январь', :]

Яблоки       150
Бананы       120
Апельсины    200
Name: Январь, dtype: int64

In [59]:
# Можно вызвать несколько строк и столбцов (не обязательно смежных)
prices_df.loc[['Январь', 'Март'], ['Яблоки', 'Апельсины']]

        Яблоки  Апельсины
Январь     150        200
Март       140        220

In [50]:
# Можно вызвать столбцы, указав их в квадратных скобках (способ 1), а строки вызвать с помощью loc
prices_df[['Яблоки', 'Апельсины']].loc[['Январь','Март']]

        Яблоки  Апельсины
Январь     150        200
Март       140        220

### Метод iloc (integer location) для выбора столбцов и строк по порядковому номеру (как в списках)

In [60]:
prices_df

         Яблоки  Бананы  Апельсины
Январь      150     120        200
Февраль     160     110        210
Март        140     100        220

In [61]:
# Вызовем значение элемента во 2 строке и в 3 столбце
# ВНИМАНИЕ: счет элементов начинается с 0
prices_df.iloc[1,2]

np.int64(210)

In [62]:
# Если нужно только первый столбец
prices_df.iloc[:,0]

Январь     150
Февраль    160
Март       140
Name: Яблоки, dtype: int64

In [63]:
# Если нужно только первую строку
prices_df.iloc[0, :]

Яблоки       150
Бананы       120
Апельсины    200
Name: Январь, dtype: int64

In [64]:
# Если нужно 1 и 3 строки и 1 и 3 столбец
prices_df.iloc[[0,2], [0,2]]

        Яблоки  Апельсины
Январь     150        200
Март       140        220

In [56]:
# Вызов последнего столбца
prices_df.iloc[:,-1]

Январь     200
Февраль    210
Март       220
Name: Апельсины, dtype: int64

In [65]:
# Вызов всех столбцов до последнего (не включая)
prices_df.iloc[:, :-1]

         Яблоки  Бананы
Январь      150     120
Февраль     160     110
Март        140     100

In [66]:
# Вызов всех строк до последней (не включая) и столбцов до последнего (не включая)
prices_df.iloc[:-1, :-1]

         Яблоки  Бананы
Январь      150     120
Февраль     160     110

### Срез по логическим условиям (аналог WHERE в SQL)

In [67]:
prices_df

         Яблоки  Бананы  Апельсины
Январь      150     120        200
Февраль     160     110        210
Март        140     100        220

Булева маска: каждая ячейка серии или датафрейма помечается True / False в зависимости от того, соответствует ли она заданному условию

In [68]:
# Создаем булеву маску по условию, что значение в ячейке превышает 150
prices_df > 150

         Яблоки  Бананы  Апельсины
Январь    False   False       True
Февраль    True   False       True
Март      False   False       True

In [69]:
# Чтобы вывести значения датафрейма, которые соответствуют заданному условию,
# нужно булеву маску поместить в квадратные скобки после названия датафрейма
prices_df[prices_df > 150]

         Яблоки  Бананы  Апельсины
Январь      NaN     NaN        200
Февраль   160.0     NaN        210
Март        NaN     NaN        220

NaN - Not a Number

NaT - Not a Time

Особый тип данных из библиотеки NumPy

In [71]:
type(prices_df[prices_df>150].iloc[0,0])

numpy.float64

In [72]:
# В SQL команда WHERE применяется по отношению к определенному столбцу (столбцам)
# Выбираются те строки таблицы, которые удовлетворяют данному условию
# Создаем булеву маску не для всего датафрейма, а только для нужного столбца
prices_df['Яблоки'] > 150

Январь     False
Февраль     True
Март       False
Name: Яблоки, dtype: bool

Аналог

SELECT яблоки, бананы, апельсины

FROM prices_df

WHERE яблоки > 150

In [73]:
prices_df[prices_df['Яблоки'] > 150]

         Яблоки  Бананы  Апельсины
Февраль     160     110        210

In [74]:
# То же с использованием loc
# Условие пишем на первом месте
prices_df.loc[prices_df['Яблоки'] > 150]

         Яблоки  Бананы  Апельсины
Февраль     160     110        210

In [75]:
# То же с использованием loc
# Условие пишем на первом месте
# Нужные столбцы пишем после запятой:
prices_df.loc[prices_df['Яблоки'] > 150, ["Яблоки", "Апельсины"]]

         Яблоки  Апельсины
Февраль     160        210

In [78]:
# Составное условие
prices_df[(prices_df['Яблоки'] > 150)|(prices_df['Апельсины'] < 210)]

         Яблоки  Бананы  Апельсины
Январь      150     120        200
Февраль     160     110        210

## Работа с индексом

In [79]:
# Вызов индекса
prices_df.index

Index(['Январь', 'Февраль', 'Март'], dtype='object')

In [80]:
# Вызов столбцов
prices_df.columns

Index(['Яблоки', 'Бананы', 'Апельсины'], dtype='object')

In [81]:
# Сброс индекса и трансформация его в обычный столбец
prices_df.reset_index(drop = False)

     index  Яблоки  Бананы  Апельсины
0   Январь     150     120        200
1  Февраль     160     110        210
2     Март     140     100        220

In [82]:
# Сброс индекса и удаление его
prices_df.reset_index(drop = True)

   Яблоки  Бананы  Апельсины
0     150     120        200
1     160     110        210
2     140     100        220

In [87]:
# Замена индекса на другой
prices_df.set_index("Яблоки", drop = False)

        Яблоки  Бананы  Апельсины
Яблоки
150        150     120        200
160        160     110        210
140        140     100        220

# Работа с таблицами в Pandas

## Загрузка данных из XLSX и CSV

Для загрузки файлов XLSX или CSV в Colab, их нужно перенести либо на Google Drive, либо загрузить во временное хранилище

### Загрузка CSV

In [90]:
customers = pd.read_csv(r"C:\Courses\Innopolis\2026\ИИ Инженер\Python Data\customer.csv")

In [91]:
customers.head(3)

,customer_id,store_id,first_name,last_name,email,address_id,activebool,create_date,last_update,active
0,524,1,Jared,Ely,jared.ely@sakilacustomer.org,530,True,2006-02-14,2013-05-26 14:49:45.738,1
1,1,1,Mary,Smith,mary.smith@sakilacustomer.org,5,True,2006-02-14,2013-05-26 14:49:45.738,1
2,2,1,Patricia,Johnson,patricia.johnson@sakilacustomer.org,6,True,2006-02-14,2013-05-26 14:49:45.738,1

### Загрузка XLSX

In [93]:
rentals = pd.read_excel(r"C:\Courses\Innopolis\2026\ИИ Инженер\Python Data\aggregated_data.xlsx", sheet_name = "rental", usecols = "A:G")

In [94]:
rentals.head(3)

,rental_id,rental_date,inventory_id,customer_id,return_date,staff_id,last_update
0,11496,2006-02-14 15:16:03,2047,155,NaT,1,2006-02-16 02:30:53
1,11541,2006-02-14 15:16:03,2026,335,NaT,1,2006-02-16 02:30:53
2,12101,2006-02-14 15:16:03,1556,479,NaT,1,2006-02-16 02:30:53

### Тонкие настройки загрузки файла эксель

In [99]:
# Загружаем сводную таблицу с листа aggregate и убираем последнюю строку с Grand Total
# Эта таблица не сохранится в памяти, а прост будет выведена на экран
pd.read_excel(r"C:\Courses\Innopolis\2026\ИИ Инженер\Python Data\aggregated_data.xlsx", sheet_name = "aggregate", skiprows = 2).iloc[:-1, :]

,Row Labels,Count of rental_id,Average of rental_length,Min of rental_date,Max of rental_date
0,167,32,3.528364,2005-05-26 18:36:58,2005-08-23 17:52:01
1,97,18,3.579205,2005-06-17 17:14:00,2005-08-22 08:20:15
2,215,26,3.599778,2005-05-29 03:49:03,2006-02-14 15:16:03
3,395,19,3.643019,2005-06-15 07:30:22,2005-08-23 19:54:24
4,401,21,3.746991,2005-05-26 02:50:31,2005-08-23 18:23:11
...,...,...,...,...,...
594,436,30,6.298449,2005-05-25 05:59:39,2005-08-23 13:10:16
595,539,22,6.319413,2005-05-26 14:30:24,2005-08-22 21:24:19
596,321,22,6.372601,2005-05-26 07:12:21,2005-08-23 16:56:14
597,187,28,6.457391,2005-05-26 14:39:53,2005-08-23 19:59:33
598,315,17,6.592622,2005-05-28 06:20:55,2006-02-14 15:16:03

## Общая характеристика датафрейма

In [100]:
# Вывести первые 3 строки датафрейма на экран
# Аналог SELECT * FROM rentals LIMIT 3
rentals.head(3)

,rental_id,rental_date,inventory_id,customer_id,return_date,staff_id,last_update
0,11496,2006-02-14 15:16:03,2047,155,NaT,1,2006-02-16 02:30:53
1,11541,2006-02-14 15:16:03,2026,335,NaT,1,2006-02-16 02:30:53
2,12101,2006-02-14 15:16:03,1556,479,NaT,1,2006-02-16 02:30:53

In [101]:
# Вывести последние 3 строки датафрейма на экран
rentals.tail(3)

,rental_id,rental_date,inventory_id,customer_id,return_date,staff_id,last_update
16041,14468,2005-08-21 13:07:10,4168,224,2005-08-30 19:05:10,2,2006-02-16 02:30:53
16042,2412,2005-06-18 16:58:58,1946,127,2005-06-27 22:57:58,1,2006-02-16 02:30:53
16043,14678,2005-08-21 20:12:43,1911,383,2005-08-31 02:11:43,2,2006-02-16 02:30:53

In [80]:
# Вывести общую сводку по датафрейму
rentals.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16044 entries, 0 to 16043
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   rental_id     16044 non-null  int64
 1   rental_date   16044 non-null  datetime64[ns]
 2   inventory_id  16044 non-null  int64
 3   customer_id   16044 non-null  int64
 4   return_date   15861 non-null  datetime64[ns]
 5   staff_id      16044 non-null  int64
 6   last_update   16044 non-null  datetime64[ns]
dtypes: datetime64[ns](3), int64(4)
memory usage: 877.5 KB

In [103]:
# Вывести размер таблицы
rentals.shape

(16044, 7)

## Сортировка (аналог ORDER BY)

### Простая сортировка по возрастанию

In [106]:
rentals = rentals.sort_values(by = "rental_id")

In [107]:
rentals.head()

,rental_id,rental_date,inventory_id,customer_id,return_date,staff_id,last_update
2742,1,2005-05-24 22:53:30,367,130,2005-05-26 22:04:30,1,2006-02-15 21:30:53
5819,2,2005-05-24 22:54:33,1525,459,2005-05-28 19:40:33,1,2006-02-16 02:30:53
13251,3,2005-05-24 23:03:39,1711,408,2005-06-01 22:12:39,1,2006-02-16 02:30:53
15524,4,2005-05-24 23:04:41,2452,333,2005-06-03 01:43:41,2,2006-02-16 02:30:53
14205,5,2005-05-24 23:05:21,2079,222,2005-06-02 04:33:21,1,2006-02-16 02:30:53

In [108]:
# Сбросим нумерацию строк с помощью метода .reset_index()
rentals = rentals.reset_index(drop = True)

In [109]:
rentals.head()

,rental_id,rental_date,inventory_id,customer_id,return_date,staff_id,last_update
0,1,2005-05-24 22:53:30,367,130,2005-05-26 22:04:30,1,2006-02-15 21:30:53
1,2,2005-05-24 22:54:33,1525,459,2005-05-28 19:40:33,1,2006-02-16 02:30:53
2,3,2005-05-24 23:03:39,1711,408,2005-06-01 22:12:39,1,2006-02-16 02:30:53
3,4,2005-05-24 23:04:41,2452,333,2005-06-03 01:43:41,2,2006-02-16 02:30:53
4,5,2005-05-24 23:05:21,2079,222,2005-06-02 04:33:21,1,2006-02-16 02:30:53

### Сортировка по двум и более столбцам

In [110]:
# Отсортируем в убывающем алфавитном порядке по фамилии
customers.sort_values(by = "last_name", ascending = False)

,customer_id,store_id,first_name,last_name,email,address_id,activebool,create_date,last_update,active
28,28,1,Cynthia,Young,cynthia.young@sakilacustomer.org,32,True,2006-02-14,2013-05-26 14:49:45.738,1
413,413,2,Marvin,Yee,marvin.yee@sakilacustomer.org,418,True,2006-02-14,2013-05-26 14:49:45.738,1
402,402,1,Luis,Yanez,luis.yanez@sakilacustomer.org,407,True,2006-02-14,2013-05-26 14:49:45.738,1
318,318,1,Brian,Wyman,brian.wyman@sakilacustomer.org,323,True,2006-02-14,2013-05-26 14:49:45.738,1
31,31,2,Brenda,Wright,brenda.wright@sakilacustomer.org,35,True,2006-02-14,2013-05-26 14:49:45.738,1
...,...,...,...,...,...,...,...,...,...,...
470,470,1,Gordon,Allard,gordon.allard@sakilacustomer.org,475,True,2006-02-14,2013-05-26 14:49:45.738,1
96,96,1,Diana,Alexander,diana.alexander@sakilacustomer.org,100,True,2006-02-14,2013-05-26 14:49:45.738,1
36,36,2,Kathleen,Adams,kathleen.adams@sakilacustomer.org,40,True,2006-02-14,2013-05-26 14:49:45.738,1
504,504,1,Nathaniel,Adam,nathaniel.adam@sakilacustomer.org,509,True,2006-02-14,2013-05-26 14:49:45.738,1
505,505,1,Rafael,Abney,rafael.abney@sakilacustomer.org,510,True,2006-02-14,2013-05-26 14:49:45.738,1

In [111]:
# Отсортируем в возрастающем порядке по имени и убывающем порядке по фамилии
customers.sort_values(by = ["first_name", "last_name"], ascending = [True, False])

,customer_id,store_id,first_name,last_name,email,address_id,activebool,create_date,last_update,active
375,375,2,Aaron,Selby,aaron.selby@sakilacustomer.org,380,True,2006-02-14,2013-05-26 14:49:45.738,1
367,367,1,Adam,Gooch,adam.gooch@sakilacustomer.org,372,True,2006-02-14,2013-05-26 14:49:45.738,1
524,525,2,Adrian,Clary,adrian.clary@sakilacustomer.org,531,True,2006-02-14,2013-05-26 14:49:45.738,1
217,217,2,Agnes,Bishop,agnes.bishop@sakilacustomer.org,221,True,2006-02-14,2013-05-26 14:49:45.738,1
389,389,1,Alan,Kahn,alan.kahn@sakilacustomer.org,394,True,2006-02-14,2013-05-26 14:49:45.738,1
...,...,...,...,...,...,...,...,...,...,...
219,219,2,Willie,Howell,willie.howell@sakilacustomer.org,223,True,2006-02-14,2013-05-26 14:49:45.738,1
212,212,2,Wilma,Richards,wilma.richards@sakilacustomer.org,216,True,2006-02-14,2013-05-26 14:49:45.738,1
190,190,2,Yolanda,Weaver,yolanda.weaver@sakilacustomer.org,194,True,2006-02-14,2013-05-26 14:49:45.738,1
174,174,2,Yvonne,Watkins,yvonne.watkins@sakilacustomer.org,178,True,2006-02-14,2013-05-26 14:49:45.738,1
479,479,1,Zachary,Hite,zachary.hite@sakilacustomer.org,484,True,2006-02-14,2013-05-26 14:49:45.738,1

## Выбор строк по условию (аналог WHERE)

### С помощью булевой маски

In [114]:
# Выберем из таблицы rentals клиента с id 375
rentals[rentals["customer_id"] == 375]

,rental_id,rental_date,inventory_id,customer_id,return_date,staff_id,last_update
306,307,2005-05-26 21:48:13,1097,375,2005-06-04 22:24:13,1,2006-02-16 02:30:53
410,412,2005-05-27 14:17:23,1400,375,2005-05-29 15:07:23,2,2006-02-16 02:30:53
747,749,2005-05-29 09:33:33,1146,375,2005-05-31 11:45:33,2,2006-02-16 02:30:53
871,873,2005-05-30 05:15:20,4568,375,2005-06-07 00:49:20,2,2006-02-16 02:30:53
1402,1404,2005-06-15 16:38:53,2776,375,2005-06-16 20:37:53,1,2006-02-16 02:30:53
1497,1499,2005-06-15 21:58:07,165,375,2005-06-22 19:37:07,2,2006-02-16 02:30:53
2234,2236,2005-06-18 04:12:33,4001,375,2005-06-23 04:07:33,1,2006-02-16 02:30:53
3978,3981,2005-07-06 23:12:12,842,375,2005-07-13 01:47:12,2,2006-02-16 02:30:53
4332,4335,2005-07-07 18:33:57,1332,375,2005-07-11 13:23:57,1,2006-02-16 02:30:53
5471,5474,2005-07-09 23:23:57,3608,375,2005-07-15 03:11:57,1,2006-02-16 02:30:53
7852,7856,2005-07-28 09:48:24,2376,375,2005-07-29 09:49:24,2,2006-02-16 02:30:53
8896,8900,2005-07-30 01:07:03,3057,375,2005-08-06 04:07:03,1,2006-02-16 02:30:53
10269,10274,2005-08-01 03:16:51,2916,375,2005-08-04 22:22:51,2,2006-02-16 02:30:53
10584,10589,2005-08-01 14:11:09,4280,375,2005-08-09 09:28:09,2,2006-02-16 02:30:53
10635,10640,2005-08-01 15:44:51,3020,375,2005-08-06 15:52:51,1,2006-02-16 02:30:53
10667,10672,2005-08-01 17:10:54,3674,375,2005-08-07 12:19:54,2,2006-02-16 02:30:53
10854,10859,2005-08-02 00:11:39,277,375,2005-08-08 19:52:39,1,2006-02-16 02:30:53
10956,10961,2005-08-02 03:47:55,1416,375,2005-08-09 02:03:55,1,2006-02-16 02:30:53
11003,11008,2005-08-02 05:06:17,2831,375,2005-08-10 01:22:17,2,2006-02-16 02:30:53
12117,12122,2005-08-17 23:20:45,4030,375,2005-08-25 04:23:45,2,2006-02-16 02:30:53
12658,12663,2005-08-18 19:10:52,1163,375,2005-08-19 15:46:52,1,2006-02-16 02:30:53
13831,13836,2005-08-20 14:18:16,4271,375,2005-08-21 18:13:16,2,2006-02-16 02:30:53
14999,15004,2005-08-22 08:15:21,4464,375,2005-08-28 10:35:21,1,2006-02-16 02:30:53
15500,15505,2005-08-23 02:46:13,1144,375,2005-08-26 23:34:13,2,2006-02-16 02:30:53

In [115]:
# Выберем из таблицы customers клиента с id 375
customers[customers["customer_id"] == 375]

,customer_id,store_id,first_name,last_name,email,address_id,activebool,create_date,last_update,active
375,375,2,Aaron,Selby,aaron.selby@sakilacustomer.org,380,True,2006-02-14,2013-05-26 14:49:45.738,1

In [116]:
# Выберем аренды, которые произошли в июле 2005 года
rentals[(rentals["rental_date"]>="2005-07-01")&(rentals["rental_date"]<"2005-08-01")]

,rental_id,rental_date,inventory_id,customer_id,return_date,staff_id,last_update
3467,3470,2005-07-05 22:49:24,883,565,2005-07-07 19:36:24,1,2006-02-16 02:30:53
3468,3471,2005-07-05 22:51:44,1724,242,2005-07-13 01:38:44,2,2006-02-16 02:30:53
3469,3472,2005-07-05 22:56:33,841,37,2005-07-13 17:18:33,2,2006-02-16 02:30:53
3470,3473,2005-07-05 22:57:34,2735,60,2005-07-12 23:53:34,1,2006-02-16 02:30:53
3471,3474,2005-07-05 22:59:53,97,594,2005-07-08 20:32:53,1,2006-02-16 02:30:53
...,...,...,...,...,...,...,...
10171,10176,2005-07-31 23:40:35,1181,19,2005-08-09 00:46:35,2,2006-02-16 02:30:53
10172,10177,2005-07-31 23:42:33,2242,279,2005-08-03 01:30:33,2,2006-02-16 02:30:53
10173,10178,2005-07-31 23:43:04,1582,491,2005-08-03 00:43:04,1,2006-02-16 02:30:53
10174,10179,2005-07-31 23:49:54,2136,131,2005-08-01 20:46:54,2,2006-02-16 02:30:53
10175,10180,2005-07-31 23:57:43,757,50,2005-08-09 04:04:43,2,2006-02-16 02:30:53

### С помощью метода query()

In [117]:
customers.query("customer_id == 375")

,customer_id,store_id,first_name,last_name,email,address_id,activebool,create_date,last_update,active
375,375,2,Aaron,Selby,aaron.selby@sakilacustomer.org,380,True,2006-02-14,2013-05-26 14:49:45.738,1

In [118]:
rentals.query("(rental_date>='2005-07-01')&(rental_date<'2005-08-01')")

,rental_id,rental_date,inventory_id,customer_id,return_date,staff_id,last_update
3467,3470,2005-07-05 22:49:24,883,565,2005-07-07 19:36:24,1,2006-02-16 02:30:53
3468,3471,2005-07-05 22:51:44,1724,242,2005-07-13 01:38:44,2,2006-02-16 02:30:53
3469,3472,2005-07-05 22:56:33,841,37,2005-07-13 17:18:33,2,2006-02-16 02:30:53
3470,3473,2005-07-05 22:57:34,2735,60,2005-07-12 23:53:34,1,2006-02-16 02:30:53
3471,3474,2005-07-05 22:59:53,97,594,2005-07-08 20:32:53,1,2006-02-16 02:30:53
...,...,...,...,...,...,...,...
10171,10176,2005-07-31 23:40:35,1181,19,2005-08-09 00:46:35,2,2006-02-16 02:30:53
10172,10177,2005-07-31 23:42:33,2242,279,2005-08-03 01:30:33,2,2006-02-16 02:30:53
10173,10178,2005-07-31 23:43:04,1582,491,2005-08-03 00:43:04,1,2006-02-16 02:30:53
10174,10179,2005-07-31 23:49:54,2136,131,2005-08-01 20:46:54,2,2006-02-16 02:30:53
10175,10180,2005-07-31 23:57:43,757,50,2005-08-09 04:04:43,2,2006-02-16 02:30:53

## Создание новых столбцов

### Создание столбца напрямую

In [119]:
# Продолжительность аренды (разность двух datetime объектов создает объект типа timedelta)
rentals["rental_length"] = rentals["return_date"] - rentals["rental_date"]
rentals.head()

,rental_id,rental_date,inventory_id,customer_id,return_date,staff_id,last_update,rental_length
0,1,2005-05-24 22:53:30,367,130,2005-05-26 22:04:30,1,2006-02-15 21:30:53,1 days 23:11:00
1,2,2005-05-24 22:54:33,1525,459,2005-05-28 19:40:33,1,2006-02-16 02:30:53,3 days 20:46:00
2,3,2005-05-24 23:03:39,1711,408,2005-06-01 22:12:39,1,2006-02-16 02:30:53,7 days 23:09:00
3,4,2005-05-24 23:04:41,2452,333,2005-06-03 01:43:41,2,2006-02-16 02:30:53,9 days 02:39:00
4,5,2005-05-24 23:05:21,2079,222,2005-06-02 04:33:21,1,2006-02-16 02:30:53,8 days 05:28:00

### С помощью метода assign

In [120]:
# внутри метода assign указываем (имя_переменной = lambda x: формула расчета переменной с использованием x в качестве заменителя имени датафрейма)
rentals = rentals.assign(rental_length2 = lambda x: x["return_date"] - x["rental_date"])
rentals.head()

,rental_id,rental_date,inventory_id,customer_id,return_date,staff_id,last_update,rental_length,rental_length2
0,1,2005-05-24 22:53:30,367,130,2005-05-26 22:04:30,1,2006-02-15 21:30:53,1 days 23:11:00,1 days 23:11:00
1,2,2005-05-24 22:54:33,1525,459,2005-05-28 19:40:33,1,2006-02-16 02:30:53,3 days 20:46:00,3 days 20:46:00
2,3,2005-05-24 23:03:39,1711,408,2005-06-01 22:12:39,1,2006-02-16 02:30:53,7 days 23:09:00,7 days 23:09:00
3,4,2005-05-24 23:04:41,2452,333,2005-06-03 01:43:41,2,2006-02-16 02:30:53,9 days 02:39:00,9 days 02:39:00
4,5,2005-05-24 23:05:21,2079,222,2005-06-02 04:33:21,1,2006-02-16 02:30:53,8 days 05:28:00,8 days 05:28:00

## Удаление столбцов

### С помощью метода .drop()

In [121]:
# axis = 1 указывает, что удалить нужно столбец с именем rental_length2
# Если нужно удалить строку, то указывается axis = 0
rentals = rentals.drop("rental_length2", axis = 1)
rentals.head()

,rental_id,rental_date,inventory_id,customer_id,return_date,staff_id,last_update,rental_length
0,1,2005-05-24 22:53:30,367,130,2005-05-26 22:04:30,1,2006-02-15 21:30:53,1 days 23:11:00
1,2,2005-05-24 22:54:33,1525,459,2005-05-28 19:40:33,1,2006-02-16 02:30:53,3 days 20:46:00
2,3,2005-05-24 23:03:39,1711,408,2005-06-01 22:12:39,1,2006-02-16 02:30:53,7 days 23:09:00
3,4,2005-05-24 23:04:41,2452,333,2005-06-03 01:43:41,2,2006-02-16 02:30:53,9 days 02:39:00
4,5,2005-05-24 23:05:21,2079,222,2005-06-02 04:33:21,1,2006-02-16 02:30:53,8 days 05:28:00

### С помощью команды del

In [122]:
del rentals["last_update"]
rentals.head()

,rental_id,rental_date,inventory_id,customer_id,return_date,staff_id,rental_length
0,1,2005-05-24 22:53:30,367,130,2005-05-26 22:04:30,1,1 days 23:11:00
1,2,2005-05-24 22:54:33,1525,459,2005-05-28 19:40:33,1,3 days 20:46:00
2,3,2005-05-24 23:03:39,1711,408,2005-06-01 22:12:39,1,7 days 23:09:00
3,4,2005-05-24 23:04:41,2452,333,2005-06-03 01:43:41,2,9 days 02:39:00
4,5,2005-05-24 23:05:21,2079,222,2005-06-02 04:33:21,1,8 days 05:28:00

## Создание новой переменной по условию (аналог CASE WHEN THEN)

### Через булеву маску (только для бинарной переменной)

In [125]:
rentals[rentals["return_date"].isna()].head(3)

,rental_id,rental_date,inventory_id,customer_id,return_date,staff_id,rental_length
11491,11496,2006-02-14 15:16:03,2047,155,NaT,1,NaT
11536,11541,2006-02-14 15:16:03,2026,335,NaT,1,NaT
11558,11563,2006-02-14 15:16:03,1545,83,NaT,1,NaT

In [126]:
# Метод .isna() проверяет, заполнена ли строка, либо там находится NaN, NaT, None и т.п.
rentals["flag_returned"] = 1 - rentals["return_date"].isna()*1
rentals.head()

,rental_id,rental_date,inventory_id,customer_id,return_date,staff_id,rental_length,flag_returned
0,1,2005-05-24 22:53:30,367,130,2005-05-26 22:04:30,1,1 days 23:11:00,1
1,2,2005-05-24 22:54:33,1525,459,2005-05-28 19:40:33,1,3 days 20:46:00,1
2,3,2005-05-24 23:03:39,1711,408,2005-06-01 22:12:39,1,7 days 23:09:00,1
3,4,2005-05-24 23:04:41,2452,333,2005-06-03 01:43:41,2,9 days 02:39:00,1
4,5,2005-05-24 23:05:21,2079,222,2005-06-02 04:33:21,1,8 days 05:28:00,1

In [128]:
rentals.tail(3)

,rental_id,rental_date,inventory_id,customer_id,return_date,staff_id,rental_length,flag_returned
16041,16047,2005-08-23 22:42:48,2088,114,2005-08-25 02:48:48,2,1 days 04:06:00,1
16042,16048,2005-08-23 22:43:07,2019,103,2005-08-31 21:33:07,1,7 days 22:50:00,1
16043,16049,2005-08-23 22:50:12,2666,393,2005-08-30 01:01:12,2,6 days 02:11:00,1

### Через функцию np.where

In [129]:
# Из библиотеки numpy вызывается команда where(условие, значение если True, значение если False)
rentals["flag_returned"] = np.where(rentals["return_date"].isna(), 0, 1)
rentals.head()

,rental_id,rental_date,inventory_id,customer_id,return_date,staff_id,rental_length,flag_returned
0,1,2005-05-24 22:53:30,367,130,2005-05-26 22:04:30,1,1 days 23:11:00,1
1,2,2005-05-24 22:54:33,1525,459,2005-05-28 19:40:33,1,3 days 20:46:00,1
2,3,2005-05-24 23:03:39,1711,408,2005-06-01 22:12:39,1,7 days 23:09:00,1
3,4,2005-05-24 23:04:41,2452,333,2005-06-03 01:43:41,2,9 days 02:39:00,1
4,5,2005-05-24 23:05:21,2079,222,2005-06-02 04:33:21,1,8 days 05:28:00,1

## Переименование столбцов

In [130]:
# С помощью метода rename
# Аргумент для rename - это словарь (dict), в котором ключ - это старое название столбца, значение - новое название столбца)
rentals.rename(columns = {"staff_id" : "employee_id"})

,rental_id,rental_date,inventory_id,customer_id,return_date,employee_id,rental_length,flag_returned
0,1,2005-05-24 22:53:30,367,130,2005-05-26 22:04:30,1,1 days 23:11:00,1
1,2,2005-05-24 22:54:33,1525,459,2005-05-28 19:40:33,1,3 days 20:46:00,1
2,3,2005-05-24 23:03:39,1711,408,2005-06-01 22:12:39,1,7 days 23:09:00,1
3,4,2005-05-24 23:04:41,2452,333,2005-06-03 01:43:41,2,9 days 02:39:00,1
4,5,2005-05-24 23:05:21,2079,222,2005-06-02 04:33:21,1,8 days 05:28:00,1
...,...,...,...,...,...,...,...,...
16039,16045,2005-08-23 22:25:26,772,14,2005-08-25 23:54:26,1,2 days 01:29:00,1
16040,16046,2005-08-23 22:26:47,4364,74,2005-08-27 18:02:47,2,3 days 19:36:00,1
16041,16047,2005-08-23 22:42:48,2088,114,2005-08-25 02:48:48,2,1 days 04:06:00,1
16042,16048,2005-08-23 22:43:07,2019,103,2005-08-31 21:33:07,1,7 days 22:50:00,1
16043,16049,2005-08-23 22:50:12,2666,393,2005-08-30 01:01:12,2,6 days 02:11:00,1

## Объединение таблиц (аналог JOIN)

In [131]:
# Простой джойн, где pandas самостоятельно определяет, по какой колонке и как его сделать
# Плохая практика, т.е. есть шансы ошибиться
pd.merge(rentals[["rental_id", "customer_id"]], customers)

,rental_id,customer_id,store_id,first_name,last_name,email,address_id,activebool,create_date,last_update,active
0,1,130,1,Charlotte,Hunter,charlotte.hunter@sakilacustomer.org,134,True,2006-02-14,2013-05-26 14:49:45.738,1
1,2,459,1,Tommy,Collazo,tommy.collazo@sakilacustomer.org,464,True,2006-02-14,2013-05-26 14:49:45.738,1
2,3,408,1,Manuel,Murrell,manuel.murrell@sakilacustomer.org,413,True,2006-02-14,2013-05-26 14:49:45.738,1
3,4,333,2,Andrew,Purdy,andrew.purdy@sakilacustomer.org,338,True,2006-02-14,2013-05-26 14:49:45.738,1
4,5,222,2,Delores,Hansen,delores.hansen@sakilacustomer.org,226,True,2006-02-14,2013-05-26 14:49:45.738,1
...,...,...,...,...,...,...,...,...,...,...,...
16039,16045,14,2,Betty,White,betty.white@sakilacustomer.org,18,True,2006-02-14,2013-05-26 14:49:45.738,1
16040,16046,74,1,Denise,Kelly,denise.kelly@sakilacustomer.org,78,True,2006-02-14,2013-05-26 14:49:45.738,1
16041,16047,114,2,Grace,Ellis,grace.ellis@sakilacustomer.org,118,True,2006-02-14,2013-05-26 14:49:45.738,1
16042,16048,103,1,Gladys,Hamilton,gladys.hamilton@sakilacustomer.org,107,True,2006-02-14,2013-05-26 14:49:45.738,1
16043,16049,393,1,Philip,Causey,philip.causey@sakilacustomer.org,398,True,2006-02-14,2013-05-26 14:49:45.738,1

In [101]:
# Хорошая практика: показать, по каким именно столбцам нужно проводить объединение
pd.merge(left = rentals, right = customers, how = "left", left_on = "customer_id", right_on = "customer_id")

,rental_id,rental_date,inventory_id,customer_id,return_date,staff_id,rental_length,flag_returned,store_id,first_name,last_name,email,address_id,activebool,create_date,last_update,active
0,1,2005-05-24 22:53:30,367,130,2005-05-26 22:04:30,1,1 days 23:11:00,1,1,Charlotte,Hunter,charlotte.hunter@sakilacustomer.org,134,True,2006-02-14,2013-05-26 14:49:45.738,1
1,2,2005-05-24 22:54:33,1525,459,2005-05-28 19:40:33,1,3 days 20:46:00,1,1,Tommy,Collazo,tommy.collazo@sakilacustomer.org,464,True,2006-02-14,2013-05-26 14:49:45.738,1
2,3,2005-05-24 23:03:39,1711,408,2005-06-01 22:12:39,1,7 days 23:09:00,1,1,Manuel,Murrell,manuel.murrell@sakilacustomer.org,413,True,2006-02-14,2013-05-26 14:49:45.738,1
3,4,2005-05-24 23:04:41,2452,333,2005-06-03 01:43:41,2,9 days 02:39:00,1,2,Andrew,Purdy,andrew.purdy@sakilacustomer.org,338,True,2006-02-14,2013-05-26 14:49:45.738,1
4,5,2005-05-24 23:05:21,2079,222,2005-06-02 04:33:21,1,8 days 05:28:00,1,2,Delores,Hansen,delores.hansen@sakilacustomer.org,226,True,2006-02-14,2013-05-26 14:49:45.738,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16039,16045,2005-08-23 22:25:26,772,14,2005-08-25 23:54:26,1,2 days 01:29:00,1,2,Betty,White,betty.white@sakilacustomer.org,18,True,2006-02-14,2013-05-26 14:49:45.738,1
16040,16046,2005-08-23 22:26:47,4364,74,2005-08-27 18:02:47,2,3 days 19:36:00,1,1,Denise,Kelly,denise.kelly@sakilacustomer.org,78,True,2006-02-14,2013-05-26 14:49:45.738,1
16041,16047,2005-08-23 22:42:48,2088,114,2005-08-25 02:48:48,2,1 days 04:06:00,1,2,Grace,Ellis,grace.ellis@sakilacustomer.org,118,True,2006-02-14,2013-05-26 14:49:45.738,1
16042,16048,2005-08-23 22:43:07,2019,103,2005-08-31 21:33:07,1,7 days 22:50:00,1,1,Gladys,Hamilton,gladys.hamilton@sakilacustomer.org,107,True,2006-02-14,2013-05-26 14:49:45.738,1
16043,16049,2005-08-23 22:50:12,2666,393,2005-08-30 01:01:12,2,6 days 02:11:00,1,1,Philip,Causey,philip.causey@sakilacustomer.org,398,True,2006-02-14,2013-05-26 14:49:45.738,1

## Примеры объединения таблиц

In [132]:
a = pd.DataFrame({"id": [1,2,3,4], "age": [30, 40, 35, 45]})
b = pd.DataFrame({"id": [1,2,3,5], "name" : ["Ivan", "Olga", "Boris", "Elena"]})

In [133]:
# Left join
pd.merge(left = a, right = b, how = "left", left_on = "id", right_on = "id")

   id  age   name
0   1   30   Ivan
1   2   40   Olga
2   3   35  Boris
3   4   45    NaN

In [134]:
# Right join
pd.merge(left = a, right = b, how = "right", left_on = "id", right_on = "id")

   id   age   name
0   1  30.0   Ivan
1   2  40.0   Olga
2   3  35.0  Boris
3   5   NaN  Elena

In [135]:
# Inner join
pd.merge(left = a, right = b, how = "inner", left_on = "id", right_on = "id")

   id  age   name
0   1   30   Ivan
1   2   40   Olga
2   3   35  Boris

In [136]:
# Full join
pd.merge(left = a, right = b, how = "outer", left_on = "id", right_on = "id")

   id   age   name
0   1  30.0   Ivan
1   2  40.0   Olga
2   3  35.0  Boris
3   4  45.0    NaN
4   5   NaN  Elena

In [138]:
# Cross join
c = pd.DataFrame({"client":[1,2,3,4], "address":["a", "b", "c", "d"]})
d = pd.DataFrame({"courier":[1,2,3,4,5], "address":["c","d","a","b","e"]})
(
    pd.merge(left = c, right = d, how = "cross", suffixes = ("_client", "_courier"))
    .query("address_client == address_courier")
)

    client address_client  courier address_courier
2        1              a        3               a
8        2              b        4               b
10       3              c        1               c
16       4              d        2               d

In [109]:
# В Pandas версии 3.0 и выше
# Left antijoin
# pd.merge(left = a, right = b, how = "left_anti", left_on = "id", right_on = "id")

In [110]:
# Right antijoin
# pd.merge(left = a, right = b, how = "right_anti", left_on = "id", right_on = "id")

## Групировка данных и агрегаты (аналог GROUP BY)

### Расчет итоговых агрегатов по датафрейму

In [139]:
payment = pd.read_csv(r"C:\Courses\Innopolis\2026\ИИ Инженер\Python Data\payment.csv")

In [140]:
# COUNT(DISTINCT customer_id) AS count_customers
# Количество уникальных значений с помощью метода nunique()
payment["customer_id"].nunique()

599

In [141]:
# AVG(amount) AS average_payment
# Среднее значение с помощью метода mean()
payment["amount"].mean()

np.float64(4.200605645382297)

In [142]:
# COUNT(amount) AS count_payments,
# Общее количество элементов с помощью метода count()
payment["amount"].count()

np.int64(14596)

In [143]:
# MIN(amount) AS minimum_payment,
# Минимум с помощью метода min()
payment["amount"].min()

0.0

In [144]:
# MAX(amount) AS maximum_payment,
# Максимум с помощью метода max()
payment["amount"].max()

11.99

In [145]:
# SUM(amount) AS total_payments,
# Сумма с помощью метода sum()
payment["amount"].sum()

np.float64(61312.040000000015)

In [146]:
# SUM(amount)/COUNT(DISTINCT customer_id) AS average_bill
payment["amount"].sum() / payment["customer_id"].nunique()

np.float64(102.35732888146914)

In [147]:
# COUNT(amount)/COUNT(DISTINCT customer_id) AS average_payments_per_client
payment["amount"].count() / payment["customer_id"].nunique()

np.float64(24.36727879799666)

In [120]:
pd.Series(
    {
        "count_customers" : payment["customer_id"].nunique(),
        "average_payment" : payment["amount"].mean(),
    }
)

count_customers    599.000000
average_payment      4.200606
dtype: float64

### Расчет агрегатов по группам

In [148]:
# Расчет количества прокатов на одного клиента
# SELECT customer_id, COUNT(rental_id) FROM rental GROUP BY customer_id
# Вариант 1: без использования команды AGG
rentals.groupby("customer_id")["rental_id"].count()

customer_id
1      32
2      27
3      26
4      22
5      38
       ..
595    30
596    28
597    25
598    22
599    19
Name: rental_id, Length: 599, dtype: int64

In [149]:
# Расчет количества прокатов на одного клиента
# Вариант 2: используя команду AGG
rentals.groupby("customer_id").agg({"rental_id":"count"})

             rental_id
customer_id
1                   32
2                   27
3                   26
4                   22
5                   38
...                ...
595                 30
596                 28
597                 25
598                 22
599                 19

[599 rows x 1 columns]

In [150]:
# Расчет среднего времени проката на каждого клиента
rentals["fact_rental_duration"] = rentals["return_date"] - rentals["rental_date"]
rentals.groupby("customer_id").agg({"fact_rental_duration":"mean"})

                 fact_rental_duration
customer_id
1              4 days 11:18:07.500000
2           5 days 12:36:06.666666666
3           5 days 21:19:25.384615384
4           3 days 22:41:05.454545454
5           5 days 01:40:12.972972973
...                               ...
595                   4 days 22:28:26
596         4 days 16:36:35.555555555
597                   4 days 16:11:55
598         5 days 19:49:08.181818181
599         5 days 12:14:50.526315789

[599 rows x 1 columns]

In [124]:
(
    rentals
    .assign(fact_rental_duration = lambda x: x["return_date"] - x["rental_date"])
    .groupby("customer_id")
    .agg({"fact_rental_duration":"mean"})
)

                 fact_rental_duration
customer_id
1              4 days 11:18:07.500000
2           5 days 12:36:06.666666666
3           5 days 21:19:25.384615384
4           3 days 22:41:05.454545454
5           5 days 01:40:12.972972973
...                               ...
595                   4 days 22:28:26
596         4 days 16:36:35.555555555
597                   4 days 16:11:55
598         5 days 19:49:08.181818181
599         5 days 12:14:50.526315789

[599 rows x 1 columns]

### Расчет нескольких агрегатов по переменным

In [125]:
# Вариант 1: через указание функций для агрегации (не рекомендуется)
(
    rentals
    .merge(payment, how = "left", on = ["rental_id", "customer_id", "staff_id"])
    .assign(fact_rental_duration = lambda x: x["return_date"] - x["rental_date"])
    .groupby("customer_id")
    .agg(
          {
              "rental_id":"count",
              "fact_rental_duration":"mean",
              "rental_date": ("min", "max"),
              "amount" : ("sum", "mean")
          }
      )
)

            rental_id      fact_rental_duration         rental_date  \
                count                      mean                 min
customer_id
1                  32    4 days 11:18:07.500000 2005-05-25 11:30:37
2                  27 5 days 12:36:06.666666666 2005-05-27 00:09:24
3                  26 5 days 21:19:25.384615384 2005-05-27 17:17:09
4                  22 3 days 22:41:05.454545454 2005-06-15 09:31:28
5                  38 5 days 01:40:12.972972973 2005-05-29 07:25:16
...               ...                       ...                 ...
595                30           4 days 22:28:26 2005-05-28 15:27:22
596                28 4 days 16:36:35.555555555 2005-05-26 21:16:52
597                25           4 days 16:11:55 2005-05-25 04:19:28
598                22 5 days 19:49:08.181818181 2005-06-20 10:10:29
599                19 5 days 12:14:50.526315789 2005-05-31 01:18:56

                                amount
                            max    sum      mean
customer_id
1           2005-08-22 20:03:46  43.85  2.923333
2           2005-08-23 17:39:35  36.91  4.101111
3           2005-08-23 07:10:14  77.87  5.990000
4           2005-08-23 07:43:00  48.89  4.444545
5           2006-02-14 15:16:03  82.80  4.140000
...                         ...    ...       ...
595         2005-08-23 21:26:35  40.89  3.717273
596         2006-02-14 15:16:03  27.89  2.535455
597         2006-02-14 15:16:03  36.91  4.101111
598         2005-08-23 00:44:15  47.87  3.682308
599         2005-08-23 11:25:00  50.89  4.626364

[599 rows x 6 columns]

In [126]:
# Вариант 2: через указание названий для каждой агрегации
(
    rentals
    .merge(payment.drop(["customer_id", "staff_id"], axis = 1), how = "left", on = ["rental_id"])
    .assign(fact_rental_duration = lambda x: x["return_date"] - x["rental_date"])
    .groupby("customer_id")
    .agg(
              number_of_rentals = ("rental_id","count"),
              average_rental_duration = ("fact_rental_duration","mean"),
              first_rental_date = ("rental_date", "min"),
              last_rental_date = ("rental_date", "max"),
              total_payments = ("amount", "sum"),
              average_bill = ("amount", "mean")
      )
)

,number_of_rentals,average_rental_duration,first_rental_date,last_rental_date,total_payments,average_bill
customer_id,,,,,,
1,32,4 days 11:18:07.500000,2005-05-25 11:30:37,2005-08-22 20:03:46,114.70,3.823333
2,27,5 days 12:36:06.666666666,2005-05-27 00:09:24,2005-08-23 17:39:35,123.74,4.759231
3,26,5 days 21:19:25.384615384,2005-05-27 17:17:09,2005-08-23 07:10:14,130.76,5.448333
4,22,3 days 22:41:05.454545454,2005-06-15 09:31:28,2005-08-23 07:43:00,81.78,3.717273
5,38,5 days 01:40:12.972972973,2005-05-29 07:25:16,2006-02-14 15:16:03,134.65,3.847143
...,...,...,...,...,...,...
595,30,4 days 22:28:26,2005-05-28 15:27:22,2005-08-23 21:26:35,110.71,3.817586
596,28,4 days 16:36:35.555555555,2005-05-26 21:16:52,2006-02-14 15:16:03,73.78,3.353636
597,25,4 days 16:11:55,2005-05-25 04:19:28,2006-02-14 15:16:03,87.77,3.816087
598,22,5 days 19:49:08.181818181,2005-06-20 10:10:29,2005-08-23 00:44:15,83.78,3.808182
599,19,5 days 12:14:50.526315789,2005-05-31 01:18:56,2005-08-23 11:25:00,78.82,4.378889

In [151]:
payment[payment["customer_id"] == 4]["amount"].sum()

np.float64(81.77999999999999)

## Сводные таблицы

In [152]:
# Как из даты получить только месяц
# Сначала с помощью метода .dt.to_period() конвертируем в интервал
# Затем с помощью метода .dt.to_timestamp() конвертируем обратно в дату
rentals["curr_month"] = rentals["rental_date"].dt.to_period(freq = "M").dt.to_timestamp()
rentals.head()

,rental_id,rental_date,inventory_id,customer_id,return_date,staff_id,rental_length,flag_returned,fact_rental_duration,curr_month
0,1,2005-05-24 22:53:30,367,130,2005-05-26 22:04:30,1,1 days 23:11:00,1,1 days 23:11:00,2005-05-01
1,2,2005-05-24 22:54:33,1525,459,2005-05-28 19:40:33,1,3 days 20:46:00,1,3 days 20:46:00,2005-05-01
2,3,2005-05-24 23:03:39,1711,408,2005-06-01 22:12:39,1,7 days 23:09:00,1,7 days 23:09:00,2005-05-01
3,4,2005-05-24 23:04:41,2452,333,2005-06-03 01:43:41,2,9 days 02:39:00,1,9 days 02:39:00,2005-05-01
4,5,2005-05-24 23:05:21,2079,222,2005-06-02 04:33:21,1,8 days 05:28:00,1,8 days 05:28:00,2005-05-01

In [153]:
# Находим первую дату для каждого клиента
rentals["first_month"] = rentals.groupby("customer_id")["curr_month"].transform("min")
rentals.head()

,rental_id,rental_date,inventory_id,customer_id,return_date,staff_id,rental_length,flag_returned,fact_rental_duration,curr_month,first_month
0,1,2005-05-24 22:53:30,367,130,2005-05-26 22:04:30,1,1 days 23:11:00,1,1 days 23:11:00,2005-05-01,2005-05-01
1,2,2005-05-24 22:54:33,1525,459,2005-05-28 19:40:33,1,3 days 20:46:00,1,3 days 20:46:00,2005-05-01,2005-05-01
2,3,2005-05-24 23:03:39,1711,408,2005-06-01 22:12:39,1,7 days 23:09:00,1,7 days 23:09:00,2005-05-01,2005-05-01
3,4,2005-05-24 23:04:41,2452,333,2005-06-03 01:43:41,2,9 days 02:39:00,1,9 days 02:39:00,2005-05-01,2005-05-01
4,5,2005-05-24 23:05:21,2079,222,2005-06-02 04:33:21,1,8 days 05:28:00,1,8 days 05:28:00,2005-05-01,2005-05-01

In [155]:
# Сводная таблица с помощью groupby
# Используем метод .unstack()
rentals.groupby(["first_month", "curr_month"]).agg({"customer_id":"nunique"}).unstack()

            customer_id
curr_month   2005-05-01 2005-06-01 2005-07-01 2005-08-01 2006-02-01
first_month
2005-05-01        520.0      512.0      520.0      520.0      139.0
2005-06-01          NaN       78.0       78.0       78.0       19.0
2005-07-01          NaN        NaN        1.0        1.0        NaN

In [156]:
# Сводная таблица с помощью функции pivot_table()
rentals.pivot_table(index = "first_month", columns = "curr_month", values = "customer_id", aggfunc = "nunique")

curr_month   2005-05-01  2005-06-01  2005-07-01  2005-08-01  2006-02-01
first_month
2005-05-01        520.0       512.0       520.0       520.0       139.0
2005-06-01          NaN        78.0        78.0        78.0        19.0
2005-07-01          NaN         NaN         1.0         1.0         NaN

In [159]:
# Сводная таблица с помощью функции pivot()
# pivot_table отличается от pivot тем, что способна обрабатывать таблицы, в которых содержатся повторяющиеся значения переменной для index и для columns
(
    rentals
    .groupby(["first_month", "curr_month"])
    .agg({"customer_id":"nunique"})
    .reset_index(drop = False)
    .pivot(index = "first_month", columns = "curr_month")
)

            customer_id
curr_month   2005-05-01 2005-06-01 2005-07-01 2005-08-01 2006-02-01
first_month
2005-05-01        520.0      512.0      520.0      520.0      139.0
2005-06-01          NaN       78.0       78.0       78.0       19.0
2005-07-01          NaN        NaN        1.0        1.0        NaN

### Разница pivot и pivot_table

In [161]:
# Пары index / column не повторяются
a = pd.DataFrame({"a": ["a1", "a1", "a2", "a2", "a3", "a3"], "b" : ["b1", "b2", "b3", "b1", "b2", "b3"], "c" : [3, 5, 7, 4, 6, 8]})
a.pivot(index = "a", columns = "b", values = "c")

b    b1   b2   b3
a
a1  3.0  5.0  NaN
a2  4.0  NaN  7.0
a3  NaN  6.0  8.0

In [164]:
# Пары index / column повторяются
b = pd.DataFrame({"a": ["a1", "a1", "a2", "a2", "a3", "a3"], "b" : ["b1", "b1", "b3", "b2", "b2", "b3"], "c" : [3, 5, 7, 4, 6, 8]})
b.pivot(index = "a", columns = "b", values = "c")

ValueError: Index contains duplicate entries, cannot reshape

In [165]:
# Пары index / column повторяются
b = pd.DataFrame({"a": ["a1", "a1", "a2", "a2", "a3", "a3"], "b" : ["b1", "b1", "b3", "b2", "b2", "b3"], "c" : [3, 5, 7, 4, 6, 8]})
b.pivot_table(index = "a", columns = "b", values = "c", aggfunc = "sum")

b    b1   b2   b3
a
a1  8.0  NaN  NaN
a2  NaN  4.0  7.0
a3  NaN  6.0  8.0

## Groupby / Transform (аналог оконных функций)

Рассчитаем процентные изменения выручки от каждого клиента по месяцам

In [169]:
# 1: трансформируем payment date из строки в datetime
# 2: трансформируем datetime в period
# 3: трансформируем period в timestamp
payment["payment_month"] = pd.to_datetime(payment["payment_date"]).dt.to_period("M").dt.to_timestamp()
monthly_payments = payment.groupby(["customer_id", "payment_month"]).agg({"amount" : "sum"}).reset_index(drop = False)
sorted_payments = monthly_payments.sort_values(by = ["customer_id", "payment_month"])
sorted_payments["amount_lag"] = sorted_payments.groupby("customer_id")["amount"].shift()
sorted_payments["pct_change"] = sorted_payments["amount"] / sorted_payments["amount_lag"] - 1
sorted_payments

      customer_id payment_month  amount  amount_lag  pct_change
0               1    2007-02-01   31.93         NaN         NaN
1               1    2007-03-01   31.89       31.93   -0.001253
2               1    2007-04-01   50.88       31.89    0.595484
3               2    2007-02-01    2.99         NaN         NaN
4               2    2007-03-01   44.89        2.99   14.013378
...           ...           ...     ...         ...         ...
1869          598    2007-03-01   15.95        2.99    4.334448
1870          598    2007-04-01   64.84       15.95    3.065204
1871          599    2007-02-01   20.96         NaN         NaN
1872          599    2007-03-01   27.93       20.96    0.332538
1873          599    2007-04-01   29.93       27.93    0.071608

[1874 rows x 5 columns]

## Работа с пропусками

### Строки с пропусками можно удалить

In [170]:
# Вариант 1: удаляем строки, которые содержат хотя бы один пропуск
sorted_payments.dropna()

      customer_id payment_month  amount  amount_lag  pct_change
1               1    2007-03-01   31.89       31.93   -0.001253
2               1    2007-04-01   50.88       31.89    0.595484
4               2    2007-03-01   44.89        2.99   14.013378
5               2    2007-04-01   75.86       44.89    0.689909
7               3    2007-03-01   35.93       25.96    0.384052
...           ...           ...     ...         ...         ...
1867          597    2007-05-01    4.99       27.92   -0.821275
1869          598    2007-03-01   15.95        2.99    4.334448
1870          598    2007-04-01   64.84       15.95    3.065204
1872          599    2007-03-01   27.93       20.96    0.332538
1873          599    2007-04-01   29.93       27.93    0.071608

[1275 rows x 5 columns]

In [171]:
# Вариант 2: удаляем строки, которые содержат пропуск в определенном столбце. Пользуемся булевой маской или query
sorted_payments[sorted_payments["pct_change"].notna()]

      customer_id payment_month  amount  amount_lag  pct_change
1               1    2007-03-01   31.89       31.93   -0.001253
2               1    2007-04-01   50.88       31.89    0.595484
4               2    2007-03-01   44.89        2.99   14.013378
5               2    2007-04-01   75.86       44.89    0.689909
7               3    2007-03-01   35.93       25.96    0.384052
...           ...           ...     ...         ...         ...
1867          597    2007-05-01    4.99       27.92   -0.821275
1869          598    2007-03-01   15.95        2.99    4.334448
1870          598    2007-04-01   64.84       15.95    3.065204
1872          599    2007-03-01   27.93       20.96    0.332538
1873          599    2007-04-01   29.93       27.93    0.071608

[1275 rows x 5 columns]

In [172]:
# Выводим строки, которые содержат пропуск в определенном столбце. Пользуемся булевой маской или query
sorted_payments[sorted_payments["pct_change"].isna()]

      customer_id payment_month  amount  amount_lag  pct_change
0               1    2007-02-01   31.93         NaN         NaN
3               2    2007-02-01    2.99         NaN         NaN
6               3    2007-02-01   25.96         NaN         NaN
9               4    2007-02-01   16.94         NaN         NaN
12              5    2007-02-01   19.95         NaN         NaN
...           ...           ...     ...         ...         ...
1857          595    2007-02-01    7.98         NaN         NaN
1860          596    2007-02-01    3.98         NaN         NaN
1864          597    2007-02-01    7.97         NaN         NaN
1868          598    2007-02-01    2.99         NaN         NaN
1871          599    2007-02-01   20.96         NaN         NaN

[599 rows x 5 columns]

### Пропуски можно заполнить

Если пропуск в ID, то такие записи лучше удалять. Вы все равно не сможете понять, кому принадлежит эта запись.

Если пропуск в дате, то надо понимать, почему он появился. Если событие еще не случилось, то можно заполнить пропуски какой-то будущей датой ("2999-01-01")

Пример: возврат аренды DVD. Те прокаты, которые еще не вернули, имеют пропуски в столбце return_date

Если пропуск в какой-то качественной характеристике (название фильма, адрес, телефон и т.п.), можно заполнить его какой-то специальной записью (например, -1 или NA, НД и т.п.)

Если пропуск в числовой переменной, то можно заполнять средней, медианой и т.п.

In [173]:
# Заполним все пропуски 0
sorted_payments.fillna(0)

      customer_id payment_month  amount  amount_lag  pct_change
0               1    2007-02-01   31.93        0.00    0.000000
1               1    2007-03-01   31.89       31.93   -0.001253
2               1    2007-04-01   50.88       31.89    0.595484
3               2    2007-02-01    2.99        0.00    0.000000
4               2    2007-03-01   44.89        2.99   14.013378
...           ...           ...     ...         ...         ...
1869          598    2007-03-01   15.95        2.99    4.334448
1870          598    2007-04-01   64.84       15.95    3.065204
1871          599    2007-02-01   20.96        0.00    0.000000
1872          599    2007-03-01   27.93       20.96    0.332538
1873          599    2007-04-01   29.93       27.93    0.071608

[1874 rows x 5 columns]

In [174]:
# Заполним пропуски amount_lag -999: и pct_change: 0
sorted_payments.fillna({"amount_lag": -999, "pct_change":0})

      customer_id payment_month  amount  amount_lag  pct_change
0               1    2007-02-01   31.93     -999.00    0.000000
1               1    2007-03-01   31.89       31.93   -0.001253
2               1    2007-04-01   50.88       31.89    0.595484
3               2    2007-02-01    2.99     -999.00    0.000000
4               2    2007-03-01   44.89        2.99   14.013378
...           ...           ...     ...         ...         ...
1869          598    2007-03-01   15.95        2.99    4.334448
1870          598    2007-04-01   64.84       15.95    3.065204
1871          599    2007-02-01   20.96     -999.00    0.000000
1872          599    2007-03-01   27.93       20.96    0.332538
1873          599    2007-04-01   29.93       27.93    0.071608

[1874 rows x 5 columns]

## Работа с дубликатами

In [175]:
c = pd.DataFrame({"a" : [10, 12, 15, 15, 20, 10, 10], "b" : [5, 8, 10, 10, 5, 5, 5]})
c

    a   b
0  10   5
1  12   8
2  15  10
3  15  10
4  20   5
5  10   5
6  10   5

In [176]:
# Дубликаты можно вывести на экран
c[c.duplicated()]

    a   b
3  15  10
5  10   5
6  10   5

In [182]:
# Удаление дубликатов
c.drop_duplicates()

    a   b
0  10   5
1  12   8
2  15  10
4  20   5

In [183]:
# Удаление дубликатов по определенному столбцу
c.drop_duplicates(subset = ["b"])

    a   b
0  10   5
1  12   8
2  15  10

In [144]:
c

    a   b
0  10   5
1  12   8
2  15  10
3  15  10
4  20   5
5  10   5
6  10   5

# Обновление библиотек

In [145]:
# Проверить версию библиотеки
pd.__version__

'2.3.3'

In [146]:
# Обновить версию библиотеки до последней
# !pip install pandas --upgrade

# Комплексные примеры по работе с таблицами

## Сбор витрины по аренде дисков (версия 1)

In [184]:
import pandas as pd

customers = (
    pd.read_csv(r"C:\Courses\Innopolis\2026\ИИ Инженер\Python Data\customer.csv")
    .assign(customer_name = lambda x: x["first_name"] + " " + x["last_name"])
    .drop(["first_name", "last_name", "activebool", "create_date", "last_update", "active", "store_id"], axis = 1)
)

rentals = (
    pd.read_csv(r"C:\Courses\Innopolis\2026\ИИ Инженер\Python Data\rental.csv")
    .assign(return_date = lambda x: pd.to_datetime(x["return_date"]))
    .assign(rental_date = lambda x: pd.to_datetime(x["rental_date"]))
    .assign(fact_rental_duration = lambda x: x["return_date"] - x["rental_date"])
    .assign(flag_returned = lambda x: np.where(x["return_date"].isna(), 0, 1))
    .loc[:, ["rental_id", "rental_date", "return_date", "fact_rental_duration", "flag_returned", "inventory_id", "customer_id", "staff_id"]]
)

inventory = (
    pd.read_csv(r"C:\Courses\Innopolis\2026\ИИ Инженер\Python Data\inventory.csv")
    .drop(["last_update", "store_id"], axis = 1)
)

film = (
    pd.read_csv(r"C:\Courses\Innopolis\2026\ИИ Инженер\Python Data\film.csv")
    .loc[:, ["film_id", "rental_duration", "title", "rental_rate"]]
    .assign(rental_duration = lambda x: pd.to_timedelta(x['rental_duration'], unit='D'))
    .rename(
        columns = {
            "rental_duration" : "normative_rental_duration",
            "title" : "film_name"
            }
        )
)

payment = (
    pd.read_csv(r"C:\Courses\Innopolis\2026\ИИ Инженер\Python Data\payment.csv")
    .drop(["customer_id", "staff_id"], axis = 1)
)

result_table = (
    rentals
    .merge(customers, how = "left", left_on = "customer_id", right_on = "customer_id")
    .merge(inventory, how = "left", left_on = "inventory_id", right_on = "inventory_id")
    .merge(film, how = "left", left_on = "film_id", right_on = "film_id")
    .merge(payment, how = "left", left_on = "rental_id", right_on = "rental_id")
    .assign(rental_overdue = lambda x: x["fact_rental_duration"] - x["normative_rental_duration"])
    .sort_values(by = "rental_date")
    .reset_index(drop = True)
)

result_table.head(5)

,rental_id,rental_date,return_date,fact_rental_duration,flag_returned,inventory_id,customer_id,staff_id,email,address_id,customer_name,film_id,normative_rental_duration,film_name,rental_rate,payment_id,amount,payment_date,rental_overdue
0,1,2005-05-24 22:53:30,2005-05-26 22:04:30,1 days 23:11:00,1,367,130,1,charlotte.hunter@sakilacustomer.org,134,Charlotte Hunter,80,7 days,Blanket Beverly,2.99,NaN,NaN,NaN,-6 days +23:11:00
1,2,2005-05-24 22:54:33,2005-05-28 19:40:33,3 days 20:46:00,1,1525,459,1,tommy.collazo@sakilacustomer.org,464,Tommy Collazo,333,7 days,Freaky Pocus,2.99,NaN,NaN,NaN,-4 days +20:46:00
2,3,2005-05-24 23:03:39,2005-06-01 22:12:39,7 days 23:09:00,1,1711,408,1,manuel.murrell@sakilacustomer.org,413,Manuel Murrell,373,7 days,Graduate Lord,2.99,NaN,NaN,NaN,0 days 23:09:00
3,4,2005-05-24 23:04:41,2005-06-03 01:43:41,9 days 02:39:00,1,2452,333,2,andrew.purdy@sakilacustomer.org,338,Andrew Purdy,535,6 days,Love Suicides,0.99,NaN,NaN,NaN,3 days 02:39:00
4,5,2005-05-24 23:05:21,2005-06-02 04:33:21,8 days 05:28:00,1,2079,222,1,delores.hansen@sakilacustomer.org,226,Delores Hansen,450,5 days,Idols Snatchers,2.99,NaN,NaN,NaN,3 days 05:28:00

## Сбор витрины по аренде дисков (версия 2)

In [185]:
import pandas as pd

customers = pd.read_csv(r"C:\Courses\Innopolis\2026\ИИ Инженер\Python Data\customer.csv")
customers["customer_name"] = customers["first_name"] + " " + customers["last_name"]
customers = customers.drop(["first_name", "last_name", "activebool", "create_date", "last_update", "active"], axis = 1)

rentals = pd.read_csv(r"C:\Courses\Innopolis\2026\ИИ Инженер\Python Data\rental.csv")
rentals["return_date"] = pd.to_datetime(rentals["return_date"])
rentals["rental_date"] = pd.to_datetime(rentals["rental_date"])
rentals["fact_rental_duration"] = rentals["return_date"] - rentals["rental_date"]
rentals["flag_returned"] = np.where(rentals["return_date"].isna(), 0, 1)
rentals = rentals.loc[:, ["rental_id", "rental_date", "return_date", "fact_rental_duration", "flag_returned", "inventory_id", "customer_id", "staff_id"]]

inventory = pd.read_csv(r"C:\Courses\Innopolis\2026\ИИ Инженер\Python Data\inventory.csv")
inventory = inventory.drop("last_update", axis = 1)

film = pd.read_csv(r"C:\Courses\Innopolis\2026\ИИ Инженер\Python Data\film.csv")
film = film.loc[:, ["film_id", "rental_duration", "title", "rental_rate"]]
film["rental_duration"] = pd.to_timedelta(film['rental_duration'], unit='D')
film = film.rename(columns = {"rental_duration" : "normative_rental_duration", "title" : "film_name"})

payment = pd.read_csv(r"C:\Courses\Innopolis\2026\ИИ Инженер\Python Data\payment.csv")
payment = payment.drop(["customer_id", "staff_id"], axis = 1)

result_table = pd.merge(left = rentals, right = customers, how = "left", left_on = "customer_id", right_on = "customer_id")
result_table = pd.merge(left = result_table, right = inventory, how = "left", left_on = "inventory_id", right_on = "inventory_id")
result_table = pd.merge(left = result_table, right = film, how = "left", left_on = "film_id", right_on = "film_id")
result_table = pd.merge(left = result_table, right = payment, how = "left", left_on = "rental_id", right_on = "rental_id")
result_table["rental_overdue"] = result_table["fact_rental_duration"] - result_table["normative_rental_duration"]
result_table = result_table.sort_values(by = "rental_date")

result_table.head()

,rental_id,rental_date,return_date,fact_rental_duration,flag_returned,inventory_id,customer_id,staff_id,store_id_x,email,...,customer_name,film_id,store_id_y,normative_rental_duration,film_name,rental_rate,payment_id,amount,payment_date,rental_overdue
16047,1,2005-05-24 22:53:30,2005-05-26 22:04:30,1 days 23:11:00,1,367,130,1,1,charlotte.hunter@sakilacustomer.org,...,Charlotte Hunter,80,1,7 days,Blanket Beverly,2.99,NaN,NaN,NaN,-6 days +23:11:00
0,2,2005-05-24 22:54:33,2005-05-28 19:40:33,3 days 20:46:00,1,1525,459,1,1,tommy.collazo@sakilacustomer.org,...,Tommy Collazo,333,2,7 days,Freaky Pocus,2.99,NaN,NaN,NaN,-4 days +20:46:00
1,3,2005-05-24 23:03:39,2005-06-01 22:12:39,7 days 23:09:00,1,1711,408,1,1,manuel.murrell@sakilacustomer.org,...,Manuel Murrell,373,2,7 days,Graduate Lord,2.99,NaN,NaN,NaN,0 days 23:09:00
2,4,2005-05-24 23:04:41,2005-06-03 01:43:41,9 days 02:39:00,1,2452,333,2,2,andrew.purdy@sakilacustomer.org,...,Andrew Purdy,535,1,6 days,Love Suicides,0.99,NaN,NaN,NaN,3 days 02:39:00
3,5,2005-05-24 23:05:21,2005-06-02 04:33:21,8 days 05:28:00,1,2079,222,1,2,delores.hansen@sakilacustomer.org,...,Delores Hansen,450,2,5 days,Idols Snatchers,2.99,NaN,NaN,NaN,3 days 05:28:00

## Сохранение датафрейма в формат csv или xlsx

### В формат csv

In [186]:
result_table.to_csv(r"C:\Courses\Innopolis\2026\ИИ Инженер\Python Data\result_data.csv")

### В формате xlsx

In [187]:
result_table.to_excel(r"C:\Courses\Innopolis\2026\ИИ Инженер\Python Data\result_data.xlsx", index = False)