# 1. Создание подключения с Psycopg

In [ ]:
pip install psycopg

In [1]:
import psycopg

**Создаем подключение к БД**

In [2]:
# Параметры для подключения к БД
DB_HOST="localhost"
DB_PORT="5432"
DB_NAME="dvdrental"
DB_USER="postgres" # В реальных проектах не следует хранить username непосредственно в коде!
DB_PASSWORD="123"  # В реальных проектах не следует хранить password непосредственно в коде!

Connection - это объект, представляющий соединение с сервером БД

In [3]:
# Создание подключения: вариант 1
conn = psycopg.connect(
    host=DB_HOST,
    port=DB_PORT,
    dbname=DB_NAME,
    user=DB_USER,
    password=DB_PASSWORD
)

In [4]:
conn

In [5]:
type(conn)

psycopg.Connection

In [6]:
# Создание подключения: вариант 2
# Синтаксис postgresql://username:password@host:port/dbname
conn_url = f"postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
conn = psycopg.connect(conn_url)

In [7]:
print(conn_url)

postgresql://postgres:123@localhost:5432/dvdrental

**Создаем курсор**

Cursor - это объект, через который Python отправляет SQL-команды и получает результаты

In [8]:
cursor = conn.cursor()

In [9]:
cursor

In [10]:
type(cursor)

psycopg.Cursor

In [15]:
cursor.execute("""
    SELECT 
        customer_id,
        first_name,
        last_name
    FROM public.customer;
""")

**Методы получения строк**

In [19]:
# Получить одну строку
row = cursor.fetchone()
print(row)

(524, 'Jared', 'Ely')

In [22]:
type(row)

tuple

In [20]:
# Получить несколько строк
rows = cursor.fetchmany(5)
for row in rows[:5]:
    print(row) # Каждая строка представлена Python tuple

In [21]:
type(rows)

list

In [23]:
rows[0]

(1, 'Mary', 'Smith')

In [24]:
for row in rows:
    print(row) # Каждая строка представлена Python tuple

(1, 'Mary', 'Smith')
(2, 'Patricia', 'Johnson')
(3, 'Linda', 'Williams')
(4, 'Barbara', 'Jones')
(5, 'Elizabeth', 'Brown')

In [25]:
# Получить все оставшиеся строки:
rows = cursor.fetchall()
for row in rows:
    print(row) # Каждая строка представлена Python tuple

(6, 'Jennifer', 'Davis')
(7, 'Maria', 'Miller')
(8, 'Susan', 'Wilson')
(9, 'Margaret', 'Moore')
(10, 'Dorothy', 'Taylor')
(11, 'Lisa', 'Anderson')
(12, 'Nancy', 'Thomas')
(13, 'Karen', 'Jackson')
(14, 'Betty', 'White')
(15, 'Helen', 'Harris')
(16, 'Sandra', 'Martin')
(17, 'Donna', 'Thompson')
(18, 'Carol', 'Garcia')
(19, 'Ruth', 'Martinez')
(20, 'Sharon', 'Robinson')
(21, 'Michelle', 'Clark')
(22, 'Laura', 'Rodriguez')
(23, 'Sarah', 'Lewis')
(24, 'Kimberly', 'Lee')
(25, 'Deborah', 'Walker')
(26, 'Jessica', 'Hall')
(27, 'Shirley', 'Allen')
(28, 'Cynthia', 'Young')
(29, 'Angela', 'Hernandez')
(30, 'Melissa', 'King')
(31, 'Brenda', 'Wright')
(32, 'Amy', 'Lopez')
(33, 'Anna', 'Hill')
(34, 'Rebecca', 'Scott')
(35, 'Virginia', 'Green')
(36, 'Kathleen', 'Adams')
(37, 'Pamela', 'Baker')
(38, 'Martha', 'Gonzalez')
(39, 'Debra', 'Nelson')
(40, 'Amanda', 'Carter')
(41, 'Stephanie', 'Mitchell')
(42, 'Carolyn', 'Perez')
(43, 'Christine', 'Roberts')
(44, 'Marie', 'Turner')
(45, 'Janet', 'Phillips')
(46, 'Catherine', 'Campbell')
(47, 'Frances', 'Parker')
(48, 'Ann', 'Evans')
(49, 'Joyce', 'Edwards')
(50, 'Diane', 'Collins')
(51, 'Alice', 'Stewart')
(52, 'Julie', 'Sanchez')
(53, 'Heather', 'Morris')
(54, 'Teresa', 'Rogers')
(55, 'Doris', 'Reed')
(56, 'Gloria', 'Cook')
(57, 'Evelyn', 'Morgan')
(58, 'Jean', 'Bell')
(59, 'Cheryl', 'Murphy')
(60, 'Mildred', 'Bailey')
(61, 'Katherine', 'Rivera')
(62, 'Joan', 'Cooper')
(63, 'Ashley', 'Richardson')
(64, 'Judith', 'Cox')
(65, 'Rose', 'Howard')
(66, 'Janice', 'Ward')
(67, 'Kelly', 'Torres')
(68, 'Nicole', 'Peterson')
(69, 'Judy', 'Gray')
(70, 'Christina', 'Ramirez')
(71, 'Kathy', 'James')
(72, 'Theresa', 'Watson')
(73, 'Beverly', 'Brooks')
(74, 'Denise', 'Kelly')
(75, 'Tammy', 'Sanders')
(76, 'Irene', 'Price')
(77, 'Jane', 'Bennett')
(78, 'Lori', 'Wood')
(79, 'Rachel', 'Barnes')
(80, 'Marilyn', 'Ross')
(81, 'Andrea', 'Henderson')
(82, 'Kathryn', 'Coleman')
(83, 'Louise', 'Jenkins')
(84, 'Sara', 'Perry')
(85, 'Anne', 'Powell')
(86, 'Jacqueline', 'Long')
(87, 'Wanda', 'Patterson')
(88, 'Bonnie', 'Hughes')
(89, 'Julia', 'Flores')
(90, 'Ruby', 'Washington')
(91, 'Lois', 'Butler')
(92, 'Tina', 'Simmons')
(93, 'Phyllis', 'Foster')
(94, 'Norma', 'Gonzales')
(95, 'Paula', 'Bryant')
(96, 'Diana', 'Alexander')
(97, 'Annie', 'Russell')
(98, 'Lillian', 'Griffin')
(99, 'Emily', 'Diaz')
(100, 'Robin', 'Hayes')
(101, 'Peggy', 'Myers')
(102, 'Crystal', 'Ford')
(103, 'Gladys', 'Hamilton')
(104, 'Rita', 'Graham')
(105, 'Dawn', 'Sullivan')
(106, 'Connie', 'Wallace')
(107, 'Florence', 'Woods')
(108, 'Tracy', 'Cole')
(109, 'Edna', 'West')
(110, 'Tiffany', 'Jordan')
(111, 'Carmen', 'Owens')
(112, 'Rosa', 'Reynolds')
(113, 'Cindy', 'Fisher')
(114, 'Grace', 'Ellis')
(115, 'Wendy', 'Harrison')
(116, 'Victoria', 'Gibson')
(117, 'Edith', 'Mcdonald')
(118, 'Kim', 'Cruz')
(119, 'Sherry', 'Marshall')
(120, 'Sylvia', 'Ortiz')
(121, 'Josephine', 'Gomez')
(122, 'Thelma', 'Murray')
(123, 'Shannon', 'Freeman')
(124, 'Sheila', 'Wells')
(125, 'Ethel', 'Webb')
(126, 'Ellen', 'Simpson')
(127, 'Elaine', 'Stevens')
(128, 'Marjorie', 'Tucker')
(129, 'Carrie', 'Porter')
(130, 'Charlotte', 'Hunter')
(131, 'Monica', 'Hicks')
(132, 'Esther', 'Crawford')
(133, 'Pauline', 'Henry')
(134, 'Emma', 'Boyd')
(135, 'Juanita', 'Mason')
(136, 'Anita', 'Morales')
(137, 'Rhonda', 'Kennedy')
(138, 'Hazel', 'Warren')
(139, 'Amber', 'Dixon')
(140, 'Eva', 'Ramos')
(141, 'Debbie', 'Reyes')
(142, 'April', 'Burns')
(143, 'Leslie', 'Gordon')
(144, 'Clara', 'Shaw')
(145, 'Lucille', 'Holmes')
(146, 'Jamie', 'Rice')
(147, 'Joanne', 'Robertson')
(148, 'Eleanor', 'Hunt')
(149, 'Valerie', 'Black')
(150, 'Danielle', 'Daniels')
(151, 'Megan', 'Palmer')
(152, 'Alicia', 'Mills')
(153, 'Suzanne', 'Nichols')
(154, 'Michele', 'Grant')
(155, 'Gail', 'Knight')
(156, 'Bertha', 'Ferguson')
(157, 'Darlene', 'Rose')
(158, 'Veronica', 'Stone')
(159, 'Jill', 'Hawkins')
(160, 'Erin', 'Dunn')
(161, 'Geraldine', 'Perkins')
(162, 'Lauren', 'Hudson')
(163, 'Cathy', 'Spencer')
(164, 'Joann', 'Gardner')
(165, 'Lorraine', 'Stephens')
(166, 'Lynn', 'Payne')
(167, 'Sally', 'Pierce')
(168, 'Regina', 'Berry')
(169, 'Erica', 'Matthews')
(170, 'Beatrice', 'Arnold')
(171, 'Dolores', 'Wagner')
(172, 'Bernice', 'Willis')
(173, 'Audrey', 'Ray')
(174, 'Yvonne', 'Watkins')
(175, 'Annette', 'Olson')
(176, 'June', 'Carroll')
(177, 'Samantha', 'Duncan')
(178, 'Marion', 'Snyder')
(179, 'Dana', 'Hart')
(180, 'Stacy', 'Cunningham')
(181, 'Ana', 'Bradley')
(182, 'Renee', 'Lane')
(183, 'Ida', 'Andrews')
(184, 'Vivian', 'Ruiz')
(185, 'Roberta', 'Harper')
(186, 'Holly', 'Fox')
(187, 'Brittany', 'Riley')
(188, 'Melanie', 'Armstrong')
(189, 'Loretta', 'Carpenter')
(190, 'Yolanda', 'Weaver')
(191, 'Jeanette', 'Greene')
(192, 'Laurie', 'Lawrence')
(193, 'Katie', 'Elliott')
(194, 'Kristen', 'Chavez')
(195, 'Vanessa', 'Sims')
(196, 'Alma', 'Austin')
(197, 'Sue', 'Peters')
(198, 'Elsie', 'Kelley')
(199, 'Beth', 'Franklin')
(200, 'Jeanne', 'Lawson')
(201, 'Vicki', 'Fields')
(202, 'Carla', 'Gutierrez')
(203, 'Tara', 'Ryan')
(204, 'Rosemary', 'Schmidt')
(205, 'Eileen', 'Carr')
(206, 'Terri', 'Vasquez')
(207, 'Gertrude', 'Castillo')
(208, 'Lucy', 'Wheeler')
(209, 'Tonya', 'Chapman')
(210, 'Ella', 'Oliver')
(211, 'Stacey', 'Montgomery')
(212, 'Wilma', 'Richards')
(213, 'Gina', 'Williamson')
(214, 'Kristin', 'Johnston')
(215, 'Jessie', 'Banks')
(216, 'Natalie', 'Meyer')
(217, 'Agnes', 'Bishop')
(218, 'Vera', 'Mccoy')
(219, 'Willie', 'Howell')
(220, 'Charlene', 'Alvarez')
(221, 'Bessie', 'Morrison')
(222, 'Delores', 'Hansen')
(223, 'Melinda', 'Fernandez')
(224, 'Pearl', 'Garza')
(225, 'Arlene', 'Harvey')
(226, 'Maureen', 'Little')
(227, 'Colleen', 'Burton')
(228, 'Allison', 'Stanley')
(229, 'Tamara', 'Nguyen')
(230, 'Joy', 'George')
(231, 'Georgia', 'Jacobs')
(232, 'Constance', 'Reid')
(233, 'Lillie', 'Kim')
(234, 'Claudia', 'Fuller')
(235, 'Jackie', 'Lynch')
(236, 'Marcia', 'Dean')
(237, 'Tanya', 'Gilbert')
(238, 'Nellie', 'Garrett')
(239, 'Minnie', 'Romero')
(240, 'Marlene', 'Welch')
(241, 'Heidi', 'Larson')
(242, 'Glenda', 'Frazier')
(243, 'Lydia', 'Burke')
(244, 'Viola', 'Hanson')
(245, 'Courtney', 'Day')
(246, 'Marian', 'Mendoza')
(247, 'Stella', 'Moreno')
(248, 'Caroline', 'Bowman')
(249, 'Dora', 'Medina')
(250, 'Jo', 'Fowler')
(251, 'Vickie', 'Brewer')
(252, 'Mattie', 'Hoffman')
(253, 'Terry', 'Carlson')
(254, 'Maxine', 'Silva')
(255, 'Irma', 'Pearson')
(256, 'Mabel', 'Holland')
(257, 'Marsha', 'Douglas')
(258, 'Myrtle', 'Fleming')
(259, 'Lena', 'Jensen')
(260, 'Christy', 'Vargas')
(261, 'Deanna', 'Byrd')
(262, 'Patsy', 'Davidson')
(263, 'Hilda', 'Hopkins')
(264, 'Gwendolyn', 'May')
(265, 'Jennie', 'Terry')
(266, 'Nora', 'Herrera')
(267, 'Margie', 'Wade')
(268, 'Nina', 'Soto')
(269, 'Cassandra', 'Walters')
(270, 'Leah', 'Curtis')
(271, 'Penny', 'Neal')
(272, 'Kay', 'Caldwell')
(273, 'Priscilla', 'Lowe')
(274, 'Naomi', 'Jennings')
(275, 'Carole', 'Barnett')
(276, 'Brandy', 'Graves')
(277, 'Olga', 'Jimenez')
(278, 'Billie', 'Horton')
(279, 'Dianne', 'Shelton')
(280, 'Tracey', 'Barrett')
(281, 'Leona', 'Obrien')
(282, 'Jenny', 'Castro')
(283, 'Felicia', 'Sutton')
(284, 'Sonia', 'Gregory')
(285, 'Miriam', 'Mckinney')
(286, 'Velma', 'Lucas')
(287, 'Becky', 'Miles')
(288, 'Bobbie', 'Craig')
(289, 'Violet', 'Rodriquez')
(290, 'Kristina', 'Chambers')
(291, 'Toni', 'Holt')
(292, 'Misty', 'Lambert')
(293, 'Mae', 'Fletcher')
(294, 'Shelly', 'Watts')
(295, 'Daisy', 'Bates')
(296, 'Ramona', 'Hale')
(297, 'Sherri', 'Rhodes')
(298, 'Erika', 'Pena')
(299, 'James', 'Gannon')
(300, 'John', 'Farnsworth')
(301, 'Robert', 'Baughman')
(302, 'Michael', 'Silverman')
(303, 'William', 'Satterfield')
(304, 'David', 'Royal')
(305, 'Richard', 'Mccrary')
(306, 'Charles', 'Kowalski')
(307, 'Joseph', 'Joy')
(308, 'Thomas', 'Grigsby')
(309, 'Christopher', 'Greco')
(310, 'Daniel', 'Cabral')
(311, 'Paul', 'Trout')
(312, 'Mark', 'Rinehart')
(313, 'Donald', 'Mahon')
(314, 'George', 'Linton')
(315, 'Kenneth', 'Gooden')
(316, 'Steven', 'Curley')
(317, 'Edward', 'Baugh')
(318, 'Brian', 'Wyman')
(319, 'Ronald', 'Weiner')
(320, 'Anthony', 'Schwab')
(321, 'Kevin', 'Schuler')
(322, 'Jason', 'Morrissey')
(323, 'Matthew', 'Mahan')
(324, 'Gary', 'Coy')
(325, 'Timothy', 'Bunn')
(326, 'Jose', 'Andrew')
(327, 'Larry', 'Thrasher')
(328, 'Jeffrey', 'Spear')
(329, 'Frank', 'Waggoner')
(330, 'Scott', 'Shelley')
(331, 'Eric', 'Robert')
(332, 'Stephen', 'Qualls')
(333, 'Andrew', 'Purdy')
(334, 'Raymond', 'Mcwhorter')
(335, 'Gregory', 'Mauldin')
(336, 'Joshua', 'Mark')
(337, 'Jerry', 'Jordon')
(338, 'Dennis', 'Gilman')
(339, 'Walter', 'Perryman')
(340, 'Patrick', 'Newsom')
(341, 'Peter', 'Menard')
(342, 'Harold', 'Martino')
(343, 'Douglas', 'Graf')
(344, 'Henry', 'Billingsley')
(345, 'Carl', 'Artis')
(346, 'Arthur', 'Simpkins')
(347, 'Ryan', 'Salisbury')
(348, 'Roger', 'Quintanilla')
(349, 'Joe', 'Gilliland')
(350, 'Juan', 'Fraley')
(351, 'Jack', 'Foust')
(352, 'Albert', 'Crouse')
(353, 'Jonathan', 'Scarborough')
(354, 'Justin', 'Ngo')
(355, 'Terry', 'Grissom')
(356, 'Gerald', 'Fultz')
(357, 'Keith', 'Rico')
(358, 'Samuel', 'Marlow')
(359, 'Willie', 'Markham')
(360, 'Ralph', 'Madrigal')
(361, 'Lawrence', 'Lawton')
(362, 'Nicholas', 'Barfield')
(363, 'Roy', 'Whiting')
(364, 'Benjamin', 'Varney')
(365, 'Bruce', 'Schwarz')
(366, 'Brandon', 'Huey')
(367, 'Adam', 'Gooch')
(368, 'Harry', 'Arce')
(369, 'Fred', 'Wheat')
(370, 'Wayne', 'Truong')
(371, 'Billy', 'Poulin')
(372, 'Steve', 'Mackenzie')
(373, 'Louis', 'Leone')
(374, 'Jeremy', 'Hurtado')
(375, 'Aaron', 'Selby')
(376, 'Randy', 'Gaither')
(377, 'Howard', 'Fortner')
(378, 'Eugene', 'Culpepper')
(379, 'Carlos', 'Coughlin')
(380, 'Russell', 'Brinson')
(381, 'Bobby', 'Boudreau')
(382, 'Victor', 'Barkley')
(383, 'Martin', 'Bales')
(384, 'Ernest', 'Stepp')
(385, 'Phillip', 'Holm')
(386, 'Todd', 'Tan')
(387, 'Jesse', 'Schilling')
(388, 'Craig', 'Morrell')
(389, 'Alan', 'Kahn')
(390, 'Shawn', 'Heaton')
(391, 'Clarence', 'Gamez')
(392, 'Sean', 'Douglass')
(393, 'Philip', 'Causey')
(394, 'Chris', 'Brothers')
(395, 'Johnny', 'Turpin')
(396, 'Earl', 'Shanks')
(397, 'Jimmy', 'Schrader')
(398, 'Antonio', 'Meek')
(399, 'Danny', 'Isom')
(400, 'Bryan', 'Hardison')
(401, 'Tony', 'Carranza')
(402, 'Luis', 'Yanez')
(403, 'Mike', 'Way')
(404, 'Stanley', 'Scroggins')
(405, 'Leonard', 'Schofield')
(406, 'Nathan', 'Runyon')
(407, 'Dale', 'Ratcliff')
(408, 'Manuel', 'Murrell')
(409, 'Rodney', 'Moeller')
(410, 'Curtis', 'Irby')
(411, 'Norman', 'Currier')
(412, 'Allen', 'Butterfield')
(413, 'Marvin', 'Yee')
(414, 'Vincent', 'Ralston')
(415, 'Glenn', 'Pullen')
(416, 'Jeffery', 'Pinson')
(417, 'Travis', 'Estep')
(418, 'Jeff', 'East')
(419, 'Chad', 'Carbone')
(420, 'Jacob', 'Lance')
(421, 'Lee', 'Hawks')
(422, 'Melvin', 'Ellington')
(423, 'Alfred', 'Casillas')
(424, 'Kyle', 'Spurlock')
(425, 'Francis', 'Sikes')
(426, 'Bradley', 'Motley')
(427, 'Jesus', 'Mccartney')
(428, 'Herbert', 'Kruger')
(429, 'Frederick', 'Isbell')
(430, 'Ray', 'Houle')
(431, 'Joel', 'Francisco')
(432, 'Edwin', 'Burk')
(433, 'Don', 'Bone')
(434, 'Eddie', 'Tomlin')
(435, 'Ricky', 'Shelby')
(436, 'Troy', 'Quigley')
(437, 'Randall', 'Neumann')
(438, 'Barry', 'Lovelace')
(439, 'Alexander', 'Fennell')
(440, 'Bernard', 'Colby')
(441, 'Mario', 'Cheatham')
(442, 'Leroy', 'Bustamante')
(443, 'Francisco', 'Skidmore')
(444, 'Marcus', 'Hidalgo')
(445, 'Micheal', 'Forman')
(446, 'Theodore', 'Culp')
(447, 'Clifford', 'Bowens')
(448, 'Miguel', 'Betancourt')
(449, 'Oscar', 'Aquino')
(450, 'Jay', 'Robb')
(451, 'Jim', 'Rea')
(452, 'Tom', 'Milner')
(453, 'Calvin', 'Martel')
(454, 'Alex', 'Gresham')
(455, 'Jon', 'Wiles')
(456, 'Ronnie', 'Ricketts')
(457, 'Bill', 'Gavin')
(458, 'Lloyd', 'Dowd')
(459, 'Tommy', 'Collazo')
(460, 'Leon', 'Bostic')
(461, 'Derek', 'Blakely')
(462, 'Warren', 'Sherrod')
(463, 'Darrell', 'Power')
(464, 'Jerome', 'Kenyon')
(465, 'Floyd', 'Gandy')
(466, 'Leo', 'Ebert')
(467, 'Alvin', 'Deloach')
(468, 'Tim', 'Cary')
(469, 'Wesley', 'Bull')
(470, 'Gordon', 'Allard')
(471, 'Dean', 'Sauer')
(472, 'Greg', 'Robins')
(473, 'Jorge', 'Olivares')
(474, 'Dustin', 'Gillette')
(475, 'Pedro', 'Chestnut')
(476, 'Derrick', 'Bourque')
(477, 'Dan', 'Paine')
(478, 'Lewis', 'Lyman')
(479, 'Zachary', 'Hite')
(480, 'Corey', 'Hauser')
(481, 'Herman', 'Devore')
(482, 'Maurice', 'Crawley')
(483, 'Vernon', 'Chapa')
(484, 'Roberto', 'Vu')
(485, 'Clyde', 'Tobias')
(486, 'Glen', 'Talbert')
(487, 'Hector', 'Poindexter')
(488, 'Shane', 'Millard')
(489, 'Ricardo', 'Meador')
(490, 'Sam', 'Mcduffie')
(491, 'Rick', 'Mattox')
(492, 'Lester', 'Kraus')
(493, 'Brent', 'Harkins')
(494, 'Ramon', 'Choate')
(495, 'Charlie', 'Bess')
(496, 'Tyler', 'Wren')
(497, 'Gilbert', 'Sledge')
(498, 'Gene', 'Sanborn')
(499, 'Marc', 'Outlaw')
(500, 'Reginald', 'Kinder')
(501, 'Ruben', 'Geary')
(502, 'Brett', 'Cornwell')
(503, 'Angel', 'Barclay')
(504, 'Nathaniel', 'Adam')
(505, 'Rafael', 'Abney')
(506, 'Leslie', 'Seward')
(507, 'Edgar', 'Rhoads')
(508, 'Milton', 'Howland')
(509, 'Raul', 'Fortier')
(510, 'Ben', 'Easter')
(511, 'Chester', 'Benner')
(512, 'Cecil', 'Vines')
(513, 'Duane', 'Tubbs')
(514, 'Franklin', 'Troutman')
(515, 'Andre', 'Rapp')
(516, 'Elmer', 'Noe')
(517, 'Brad', 'Mccurdy')
(518, 'Gabriel', 'Harder')
(519, 'Ron', 'Deluca')
(520, 'Mitchell', 'Westmoreland')
(521, 'Roland', 'South')
(522, 'Arnold', 'Havens')
(523, 'Harvey', 'Guajardo')
(525, 'Adrian', 'Clary')
(526, 'Karl', 'Seal')
(527, 'Cory', 'Meehan')
(528, 'Claude', 'Herzog')
(529, 'Erik', 'Guillen')
(530, 'Darryl', 'Ashcraft')
(531, 'Jamie', 'Waugh')
(532, 'Neil', 'Renner')
(533, 'Jessie', 'Milam')
(534, 'Christian', 'Jung')
(535, 'Javier', 'Elrod')
(536, 'Fernando', 'Churchill')
(537, 'Clinton', 'Buford')
(538, 'Ted', 'Breaux')
(539, 'Mathew', 'Bolin')
(540, 'Tyrone', 'Asher')
(541, 'Darren', 'Windham')
(542, 'Lonnie', 'Tirado')
(543, 'Lance', 'Pemberton')
(544, 'Cody', 'Nolen')
(545, 'Julio', 'Noland')
(546, 'Kelly', 'Knott')
(547, 'Kurt', 'Emmons')
(548, 'Allan', 'Cornish')
(549, 'Nelson', 'Christenson')
(550, 'Guy', 'Brownlee')
(551, 'Clayton', 'Barbee')
(552, 'Hugh', 'Waldrop')
(553, 'Max', 'Pitt')
(554, 'Dwayne', 'Olvera')
(555, 'Dwight', 'Lombardi')
(556, 'Armando', 'Gruber')
(557, 'Felix', 'Gaffney')
(558, 'Jimmie', 'Eggleston')
(559, 'Everett', 'Banda')
(560, 'Jordan', 'Archuleta')
(561, 'Ian', 'Still')
(562, 'Wallace', 'Slone')
(563, 'Ken', 'Prewitt')
(564, 'Bob', 'Pfeiffer')
(565, 'Jaime', 'Nettles')
(566, 'Casey', 'Mena')
(567, 'Alfredo', 'Mcadams')
(568, 'Alberto', 'Henning')
(569, 'Dave', 'Gardiner')
(570, 'Ivan', 'Cromwell')
(571, 'Johnnie', 'Chisholm')
(572, 'Sidney', 'Burleson')
(573, 'Byron', 'Box')
(574, 'Julian', 'Vest')
(575, 'Isaac', 'Oglesby')
(576, 'Morris', 'Mccarter')
(577, 'Clifton', 'Malcolm')
(578, 'Willard', 'Lumpkin')
(579, 'Daryl', 'Larue')
(580, 'Ross', 'Grey')
(581, 'Virgil', 'Wofford')
(582, 'Andy', 'Vanhorn')
(583, 'Marshall', 'Thorn')
(584, 'Salvador', 'Teel')
(585, 'Perry', 'Swafford')
(586, 'Kirk', 'Stclair')
(587, 'Sergio', 'Stanfield')
(588, 'Marion', 'Ocampo')
(589, 'Tracy', 'Herrmann')
(590, 'Seth', 'Hannon')
(591, 'Kent', 'Arsenault')
(592, 'Terrance', 'Roush')
(593, 'Rene', 'Mcalister')
(594, 'Eduardo', 'Hiatt')
(595, 'Terrence', 'Gunderson')
(596, 'Enrique', 'Forsythe')
(597, 'Freddie', 'Duggan')
(598, 'Wade', 'Delvalle')
(599, 'Austin', 'Cintron')
(609, 'Петр', 'Николаев')

**Осторожно**: если запрос вернул 50 000 000 строк, то Python попытается загрузить их в память!!

In [28]:
cursor.close() # закрываем курсор соединение с PostgreSQL 
conn.close()   # закрывает соединение с PostgreSQL

**Попробуем собрать из кортежей dataframe**

In [29]:
import pandas as pd

In [39]:
conn_url = f"postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
conn = psycopg.connect(conn_url)
cursor = conn.cursor()

cursor.execute("""
    SELECT 
        customer_id,
        first_name,
        last_name
    FROM public.customer;
""")

col_names = ("customer_id", "first_name", "last_name")
df = pd.DataFrame(columns = list(col_names))
i = 0
while True:
    row = cursor.fetchone()
    if row is None:
        break
    temp_df = pd.DataFrame(dict(zip(col_names, row)), index = [i])
    df = pd.concat([df, temp_df])
    i+=1

In [40]:
df.shape

(600, 3)

In [42]:
df.head()

  customer_id first_name last_name
0         524      Jared       Ely
1           1       Mary     Smith
2           2   Patricia   Johnson
3           3      Linda  Williams
4           4    Barbara     Jones

# 2. Параметризованные запросы

In [43]:
# Плохая практика:
customer_id = 100

conn = psycopg.connect(conn_url)
cursor = conn.cursor()
cursor.execute(
    f"""
        SELECT *
        FROM customer
        WHERE customer_id = {customer_id}
    """
)

rows = cursor.fetchall()
for row in rows:
    print(row)
    
cursor.close()
conn.close()

(100, 1, 'Robin', 'Hayes', 'robin.hayes@sakilacustomer.org', 104, True, datetime.date(2006, 2, 14), datetime.datetime(2013, 5, 26, 14, 49, 45, 738000), 1)

In [45]:
# Рекомендуется:
customer_id = 100

conn = psycopg.connect(conn_url)
cursor = conn.cursor()
cursor.execute(
    """
        SELECT *
        FROM customer
        WHERE customer_id = %s
    """,
    (customer_id,)
)

rows = cursor.fetchall()
for row in rows:
    print(row)
    
cursor.close()
conn.close()

(100, 1, 'Robin', 'Hayes', 'robin.hayes@sakilacustomer.org', 104, True, datetime.date(2006, 2, 14), datetime.datetime(2013, 5, 26, 14, 49, 45, 738000), 1)

**Пример SQL инъекции**

Если ввести Mary, то все ок

А если ввести *' OR '1'='1* ??

In [47]:
name = input("Введите имя клиента: ")

conn = psycopg.connect(conn_url)
cursor = conn.cursor()
query = f"""
    SELECT
        customer_id,
        first_name,
        last_name,
        email
    FROM customer
    WHERE first_name = '{name}';
"""

cursor.execute(query)

for row in cursor.fetchall():
    print(row)

cursor.close()
conn.close()

Введите имя клиента:  ' OR '1' = '1

(524, 'Jared', 'Ely', 'jared.ely@sakilacustomer.org')
(1, 'Mary', 'Smith', 'mary.smith@sakilacustomer.org')
(2, 'Patricia', 'Johnson', 'patricia.johnson@sakilacustomer.org')
(3, 'Linda', 'Williams', 'linda.williams@sakilacustomer.org')
(4, 'Barbara', 'Jones', 'barbara.jones@sakilacustomer.org')
(5, 'Elizabeth', 'Brown', 'elizabeth.brown@sakilacustomer.org')
(6, 'Jennifer', 'Davis', 'jennifer.davis@sakilacustomer.org')
(7, 'Maria', 'Miller', 'maria.miller@sakilacustomer.org')
(8, 'Susan', 'Wilson', 'susan.wilson@sakilacustomer.org')
(9, 'Margaret', 'Moore', 'margaret.moore@sakilacustomer.org')
(10, 'Dorothy', 'Taylor', 'dorothy.taylor@sakilacustomer.org')
(11, 'Lisa', 'Anderson', 'lisa.anderson@sakilacustomer.org')
(12, 'Nancy', 'Thomas', 'nancy.thomas@sakilacustomer.org')
(13, 'Karen', 'Jackson', 'karen.jackson@sakilacustomer.org')
(14, 'Betty', 'White', 'betty.white@sakilacustomer.org')
(15, 'Helen', 'Harris', 'helen.harris@sakilacustomer.org')
(16, 'Sandra', 'Martin', 'sandra.martin@sakilacustomer.org')
(17, 'Donna', 'Thompson', 'donna.thompson@sakilacustomer.org')
(18, 'Carol', 'Garcia', 'carol.garcia@sakilacustomer.org')
(19, 'Ruth', 'Martinez', 'ruth.martinez@sakilacustomer.org')
(20, 'Sharon', 'Robinson', 'sharon.robinson@sakilacustomer.org')
(21, 'Michelle', 'Clark', 'michelle.clark@sakilacustomer.org')
(22, 'Laura', 'Rodriguez', 'laura.rodriguez@sakilacustomer.org')
(23, 'Sarah', 'Lewis', 'sarah.lewis@sakilacustomer.org')
(24, 'Kimberly', 'Lee', 'kimberly.lee@sakilacustomer.org')
(25, 'Deborah', 'Walker', 'deborah.walker@sakilacustomer.org')
(26, 'Jessica', 'Hall', 'jessica.hall@sakilacustomer.org')
(27, 'Shirley', 'Allen', 'shirley.allen@sakilacustomer.org')
(28, 'Cynthia', 'Young', 'cynthia.young@sakilacustomer.org')
(29, 'Angela', 'Hernandez', 'angela.hernandez@sakilacustomer.org')
(30, 'Melissa', 'King', 'melissa.king@sakilacustomer.org')
(31, 'Brenda', 'Wright', 'brenda.wright@sakilacustomer.org')
(32, 'Amy', 'Lopez', 'amy.lopez@sakilacustomer.org')
(33, 'Anna', 'Hill', 'anna.hill@sakilacustomer.org')
(34, 'Rebecca', 'Scott', 'rebecca.scott@sakilacustomer.org')
(35, 'Virginia', 'Green', 'virginia.green@sakilacustomer.org')
(36, 'Kathleen', 'Adams', 'kathleen.adams@sakilacustomer.org')
(37, 'Pamela', 'Baker', 'pamela.baker@sakilacustomer.org')
(38, 'Martha', 'Gonzalez', 'martha.gonzalez@sakilacustomer.org')
(39, 'Debra', 'Nelson', 'debra.nelson@sakilacustomer.org')
(40, 'Amanda', 'Carter', 'amanda.carter@sakilacustomer.org')
(41, 'Stephanie', 'Mitchell', 'stephanie.mitchell@sakilacustomer.org')
(42, 'Carolyn', 'Perez', 'carolyn.perez@sakilacustomer.org')
(43, 'Christine', 'Roberts', 'christine.roberts@sakilacustomer.org')
(44, 'Marie', 'Turner', 'marie.turner@sakilacustomer.org')
(45, 'Janet', 'Phillips', 'janet.phillips@sakilacustomer.org')
(46, 'Catherine', 'Campbell', 'catherine.campbell@sakilacustomer.org')
(47, 'Frances', 'Parker', 'frances.parker@sakilacustomer.org')
(48, 'Ann', 'Evans', 'ann.evans@sakilacustomer.org')
(49, 'Joyce', 'Edwards', 'joyce.edwards@sakilacustomer.org')
(50, 'Diane', 'Collins', 'diane.collins@sakilacustomer.org')
(51, 'Alice', 'Stewart', 'alice.stewart@sakilacustomer.org')
(52, 'Julie', 'Sanchez', 'julie.sanchez@sakilacustomer.org')
(53, 'Heather', 'Morris', 'heather.morris@sakilacustomer.org')
(54, 'Teresa', 'Rogers', 'teresa.rogers@sakilacustomer.org')
(55, 'Doris', 'Reed', 'doris.reed@sakilacustomer.org')
(56, 'Gloria', 'Cook', 'gloria.cook@sakilacustomer.org')
(57, 'Evelyn', 'Morgan', 'evelyn.morgan@sakilacustomer.org')
(58, 'Jean', 'Bell', 'jean.bell@sakilacustomer.org')
(59, 'Cheryl', 'Murphy', 'cheryl.murphy@sakilacustomer.org')
(60, 'Mildred', 'Bailey', 'mildred.bailey@sakilacustomer.org')
(61, 'Katherine', 'Rivera', 'katherine.rivera@sakilacustomer.org')
(62, 'Joan', 'Cooper', 'joan.cooper@sakilacustomer.org')
(63, 'Ashley', 'Richardson', 'ashley.richardson@sakilacustomer.org')
(64, 'Judith', 'Cox', 'judith.cox@sakilacustomer.org')
(65, 'Rose', 'Howard', 'rose.howard@sakilacustomer.org')
(66, 'Janice', 'Ward', 'janice.ward@sakilacustomer.org')
(67, 'Kelly', 'Torres', 'kelly.torres@sakilacustomer.org')
(68, 'Nicole', 'Peterson', 'nicole.peterson@sakilacustomer.org')
(69, 'Judy', 'Gray', 'judy.gray@sakilacustomer.org')
(70, 'Christina', 'Ramirez', 'christina.ramirez@sakilacustomer.org')
(71, 'Kathy', 'James', 'kathy.james@sakilacustomer.org')
(72, 'Theresa', 'Watson', 'theresa.watson@sakilacustomer.org')
(73, 'Beverly', 'Brooks', 'beverly.brooks@sakilacustomer.org')
(74, 'Denise', 'Kelly', 'denise.kelly@sakilacustomer.org')
(75, 'Tammy', 'Sanders', 'tammy.sanders@sakilacustomer.org')
(76, 'Irene', 'Price', 'irene.price@sakilacustomer.org')
(77, 'Jane', 'Bennett', 'jane.bennett@sakilacustomer.org')
(78, 'Lori', 'Wood', 'lori.wood@sakilacustomer.org')
(79, 'Rachel', 'Barnes', 'rachel.barnes@sakilacustomer.org')
(80, 'Marilyn', 'Ross', 'marilyn.ross@sakilacustomer.org')
(81, 'Andrea', 'Henderson', 'andrea.henderson@sakilacustomer.org')
(82, 'Kathryn', 'Coleman', 'kathryn.coleman@sakilacustomer.org')
(83, 'Louise', 'Jenkins', 'louise.jenkins@sakilacustomer.org')
(84, 'Sara', 'Perry', 'sara.perry@sakilacustomer.org')
(85, 'Anne', 'Powell', 'anne.powell@sakilacustomer.org')
(86, 'Jacqueline', 'Long', 'jacqueline.long@sakilacustomer.org')
(87, 'Wanda', 'Patterson', 'wanda.patterson@sakilacustomer.org')
(88, 'Bonnie', 'Hughes', 'bonnie.hughes@sakilacustomer.org')
(89, 'Julia', 'Flores', 'julia.flores@sakilacustomer.org')
(90, 'Ruby', 'Washington', 'ruby.washington@sakilacustomer.org')
(91, 'Lois', 'Butler', 'lois.butler@sakilacustomer.org')
(92, 'Tina', 'Simmons', 'tina.simmons@sakilacustomer.org')
(93, 'Phyllis', 'Foster', 'phyllis.foster@sakilacustomer.org')
(94, 'Norma', 'Gonzales', 'norma.gonzales@sakilacustomer.org')
(95, 'Paula', 'Bryant', 'paula.bryant@sakilacustomer.org')
(96, 'Diana', 'Alexander', 'diana.alexander@sakilacustomer.org')
(97, 'Annie', 'Russell', 'annie.russell@sakilacustomer.org')
(98, 'Lillian', 'Griffin', 'lillian.griffin@sakilacustomer.org')
(99, 'Emily', 'Diaz', 'emily.diaz@sakilacustomer.org')
(100, 'Robin', 'Hayes', 'robin.hayes@sakilacustomer.org')
(101, 'Peggy', 'Myers', 'peggy.myers@sakilacustomer.org')
(102, 'Crystal', 'Ford', 'crystal.ford@sakilacustomer.org')
(103, 'Gladys', 'Hamilton', 'gladys.hamilton@sakilacustomer.org')
(104, 'Rita', 'Graham', 'rita.graham@sakilacustomer.org')
(105, 'Dawn', 'Sullivan', 'dawn.sullivan@sakilacustomer.org')
(106, 'Connie', 'Wallace', 'connie.wallace@sakilacustomer.org')
(107, 'Florence', 'Woods', 'florence.woods@sakilacustomer.org')
(108, 'Tracy', 'Cole', 'tracy.cole@sakilacustomer.org')
(109, 'Edna', 'West', 'edna.west@sakilacustomer.org')
(110, 'Tiffany', 'Jordan', 'tiffany.jordan@sakilacustomer.org')
(111, 'Carmen', 'Owens', 'carmen.owens@sakilacustomer.org')
(112, 'Rosa', 'Reynolds', 'rosa.reynolds@sakilacustomer.org')
(113, 'Cindy', 'Fisher', 'cindy.fisher@sakilacustomer.org')
(114, 'Grace', 'Ellis', 'grace.ellis@sakilacustomer.org')
(115, 'Wendy', 'Harrison', 'wendy.harrison@sakilacustomer.org')
(116, 'Victoria', 'Gibson', 'victoria.gibson@sakilacustomer.org')
(117, 'Edith', 'Mcdonald', 'edith.mcdonald@sakilacustomer.org')
(118, 'Kim', 'Cruz', 'kim.cruz@sakilacustomer.org')
(119, 'Sherry', 'Marshall', 'sherry.marshall@sakilacustomer.org')
(120, 'Sylvia', 'Ortiz', 'sylvia.ortiz@sakilacustomer.org')
(121, 'Josephine', 'Gomez', 'josephine.gomez@sakilacustomer.org')
(122, 'Thelma', 'Murray', 'thelma.murray@sakilacustomer.org')
(123, 'Shannon', 'Freeman', 'shannon.freeman@sakilacustomer.org')
(124, 'Sheila', 'Wells', 'sheila.wells@sakilacustomer.org')
(125, 'Ethel', 'Webb', 'ethel.webb@sakilacustomer.org')
(126, 'Ellen', 'Simpson', 'ellen.simpson@sakilacustomer.org')
(127, 'Elaine', 'Stevens', 'elaine.stevens@sakilacustomer.org')
(128, 'Marjorie', 'Tucker', 'marjorie.tucker@sakilacustomer.org')
(129, 'Carrie', 'Porter', 'carrie.porter@sakilacustomer.org')
(130, 'Charlotte', 'Hunter', 'charlotte.hunter@sakilacustomer.org')
(131, 'Monica', 'Hicks', 'monica.hicks@sakilacustomer.org')
(132, 'Esther', 'Crawford', 'esther.crawford@sakilacustomer.org')
(133, 'Pauline', 'Henry', 'pauline.henry@sakilacustomer.org')
(134, 'Emma', 'Boyd', 'emma.boyd@sakilacustomer.org')
(135, 'Juanita', 'Mason', 'juanita.mason@sakilacustomer.org')
(136, 'Anita', 'Morales', 'anita.morales@sakilacustomer.org')
(137, 'Rhonda', 'Kennedy', 'rhonda.kennedy@sakilacustomer.org')
(138, 'Hazel', 'Warren', 'hazel.warren@sakilacustomer.org')
(139, 'Amber', 'Dixon', 'amber.dixon@sakilacustomer.org')
(140, 'Eva', 'Ramos', 'eva.ramos@sakilacustomer.org')
(141, 'Debbie', 'Reyes', 'debbie.reyes@sakilacustomer.org')
(142, 'April', 'Burns', 'april.burns@sakilacustomer.org')
(143, 'Leslie', 'Gordon', 'leslie.gordon@sakilacustomer.org')
(144, 'Clara', 'Shaw', 'clara.shaw@sakilacustomer.org')
(145, 'Lucille', 'Holmes', 'lucille.holmes@sakilacustomer.org')
(146, 'Jamie', 'Rice', 'jamie.rice@sakilacustomer.org')
(147, 'Joanne', 'Robertson', 'joanne.robertson@sakilacustomer.org')
(148, 'Eleanor', 'Hunt', 'eleanor.hunt@sakilacustomer.org')
(149, 'Valerie', 'Black', 'valerie.black@sakilacustomer.org')
(150, 'Danielle', 'Daniels', 'danielle.daniels@sakilacustomer.org')
(151, 'Megan', 'Palmer', 'megan.palmer@sakilacustomer.org')
(152, 'Alicia', 'Mills', 'alicia.mills@sakilacustomer.org')
(153, 'Suzanne', 'Nichols', 'suzanne.nichols@sakilacustomer.org')
(154, 'Michele', 'Grant', 'michele.grant@sakilacustomer.org')
(155, 'Gail', 'Knight', 'gail.knight@sakilacustomer.org')
(156, 'Bertha', 'Ferguson', 'bertha.ferguson@sakilacustomer.org')
(157, 'Darlene', 'Rose', 'darlene.rose@sakilacustomer.org')
(158, 'Veronica', 'Stone', 'veronica.stone@sakilacustomer.org')
(159, 'Jill', 'Hawkins', 'jill.hawkins@sakilacustomer.org')
(160, 'Erin', 'Dunn', 'erin.dunn@sakilacustomer.org')
(161, 'Geraldine', 'Perkins', 'geraldine.perkins@sakilacustomer.org')
(162, 'Lauren', 'Hudson', 'lauren.hudson@sakilacustomer.org')
(163, 'Cathy', 'Spencer', 'cathy.spencer@sakilacustomer.org')
(164, 'Joann', 'Gardner', 'joann.gardner@sakilacustomer.org')
(165, 'Lorraine', 'Stephens', 'lorraine.stephens@sakilacustomer.org')
(166, 'Lynn', 'Payne', 'lynn.payne@sakilacustomer.org')
(167, 'Sally', 'Pierce', 'sally.pierce@sakilacustomer.org')
(168, 'Regina', 'Berry', 'regina.berry@sakilacustomer.org')
(169, 'Erica', 'Matthews', 'erica.matthews@sakilacustomer.org')
(170, 'Beatrice', 'Arnold', 'beatrice.arnold@sakilacustomer.org')
(171, 'Dolores', 'Wagner', 'dolores.wagner@sakilacustomer.org')
(172, 'Bernice', 'Willis', 'bernice.willis@sakilacustomer.org')
(173, 'Audrey', 'Ray', 'audrey.ray@sakilacustomer.org')
(174, 'Yvonne', 'Watkins', 'yvonne.watkins@sakilacustomer.org')
(175, 'Annette', 'Olson', 'annette.olson@sakilacustomer.org')
(176, 'June', 'Carroll', 'june.carroll@sakilacustomer.org')
(177, 'Samantha', 'Duncan', 'samantha.duncan@sakilacustomer.org')
(178, 'Marion', 'Snyder', 'marion.snyder@sakilacustomer.org')
(179, 'Dana', 'Hart', 'dana.hart@sakilacustomer.org')
(180, 'Stacy', 'Cunningham', 'stacy.cunningham@sakilacustomer.org')
(181, 'Ana', 'Bradley', 'ana.bradley@sakilacustomer.org')
(182, 'Renee', 'Lane', 'renee.lane@sakilacustomer.org')
(183, 'Ida', 'Andrews', 'ida.andrews@sakilacustomer.org')
(184, 'Vivian', 'Ruiz', 'vivian.ruiz@sakilacustomer.org')
(185, 'Roberta', 'Harper', 'roberta.harper@sakilacustomer.org')
(186, 'Holly', 'Fox', 'holly.fox@sakilacustomer.org')
(187, 'Brittany', 'Riley', 'brittany.riley@sakilacustomer.org')
(188, 'Melanie', 'Armstrong', 'melanie.armstrong@sakilacustomer.org')
(189, 'Loretta', 'Carpenter', 'loretta.carpenter@sakilacustomer.org')
(190, 'Yolanda', 'Weaver', 'yolanda.weaver@sakilacustomer.org')
(191, 'Jeanette', 'Greene', 'jeanette.greene@sakilacustomer.org')
(192, 'Laurie', 'Lawrence', 'laurie.lawrence@sakilacustomer.org')
(193, 'Katie', 'Elliott', 'katie.elliott@sakilacustomer.org')
(194, 'Kristen', 'Chavez', 'kristen.chavez@sakilacustomer.org')
(195, 'Vanessa', 'Sims', 'vanessa.sims@sakilacustomer.org')
(196, 'Alma', 'Austin', 'alma.austin@sakilacustomer.org')
(197, 'Sue', 'Peters', 'sue.peters@sakilacustomer.org')
(198, 'Elsie', 'Kelley', 'elsie.kelley@sakilacustomer.org')
(199, 'Beth', 'Franklin', 'beth.franklin@sakilacustomer.org')
(200, 'Jeanne', 'Lawson', 'jeanne.lawson@sakilacustomer.org')
(201, 'Vicki', 'Fields', 'vicki.fields@sakilacustomer.org')
(202, 'Carla', 'Gutierrez', 'carla.gutierrez@sakilacustomer.org')
(203, 'Tara', 'Ryan', 'tara.ryan@sakilacustomer.org')
(204, 'Rosemary', 'Schmidt', 'rosemary.schmidt@sakilacustomer.org')
(205, 'Eileen', 'Carr', 'eileen.carr@sakilacustomer.org')
(206, 'Terri', 'Vasquez', 'terri.vasquez@sakilacustomer.org')
(207, 'Gertrude', 'Castillo', 'gertrude.castillo@sakilacustomer.org')
(208, 'Lucy', 'Wheeler', 'lucy.wheeler@sakilacustomer.org')
(209, 'Tonya', 'Chapman', 'tonya.chapman@sakilacustomer.org')
(210, 'Ella', 'Oliver', 'ella.oliver@sakilacustomer.org')
(211, 'Stacey', 'Montgomery', 'stacey.montgomery@sakilacustomer.org')
(212, 'Wilma', 'Richards', 'wilma.richards@sakilacustomer.org')
(213, 'Gina', 'Williamson', 'gina.williamson@sakilacustomer.org')
(214, 'Kristin', 'Johnston', 'kristin.johnston@sakilacustomer.org')
(215, 'Jessie', 'Banks', 'jessie.banks@sakilacustomer.org')
(216, 'Natalie', 'Meyer', 'natalie.meyer@sakilacustomer.org')
(217, 'Agnes', 'Bishop', 'agnes.bishop@sakilacustomer.org')
(218, 'Vera', 'Mccoy', 'vera.mccoy@sakilacustomer.org')
(219, 'Willie', 'Howell', 'willie.howell@sakilacustomer.org')
(220, 'Charlene', 'Alvarez', 'charlene.alvarez@sakilacustomer.org')
(221, 'Bessie', 'Morrison', 'bessie.morrison@sakilacustomer.org')
(222, 'Delores', 'Hansen', 'delores.hansen@sakilacustomer.org')
(223, 'Melinda', 'Fernandez', 'melinda.fernandez@sakilacustomer.org')
(224, 'Pearl', 'Garza', 'pearl.garza@sakilacustomer.org')
(225, 'Arlene', 'Harvey', 'arlene.harvey@sakilacustomer.org')
(226, 'Maureen', 'Little', 'maureen.little@sakilacustomer.org')
(227, 'Colleen', 'Burton', 'colleen.burton@sakilacustomer.org')
(228, 'Allison', 'Stanley', 'allison.stanley@sakilacustomer.org')
(229, 'Tamara', 'Nguyen', 'tamara.nguyen@sakilacustomer.org')
(230, 'Joy', 'George', 'joy.george@sakilacustomer.org')
(231, 'Georgia', 'Jacobs', 'georgia.jacobs@sakilacustomer.org')
(232, 'Constance', 'Reid', 'constance.reid@sakilacustomer.org')
(233, 'Lillie', 'Kim', 'lillie.kim@sakilacustomer.org')
(234, 'Claudia', 'Fuller', 'claudia.fuller@sakilacustomer.org')
(235, 'Jackie', 'Lynch', 'jackie.lynch@sakilacustomer.org')
(236, 'Marcia', 'Dean', 'marcia.dean@sakilacustomer.org')
(237, 'Tanya', 'Gilbert', 'tanya.gilbert@sakilacustomer.org')
(238, 'Nellie', 'Garrett', 'nellie.garrett@sakilacustomer.org')
(239, 'Minnie', 'Romero', 'minnie.romero@sakilacustomer.org')
(240, 'Marlene', 'Welch', 'marlene.welch@sakilacustomer.org')
(241, 'Heidi', 'Larson', 'heidi.larson@sakilacustomer.org')
(242, 'Glenda', 'Frazier', 'glenda.frazier@sakilacustomer.org')
(243, 'Lydia', 'Burke', 'lydia.burke@sakilacustomer.org')
(244, 'Viola', 'Hanson', 'viola.hanson@sakilacustomer.org')
(245, 'Courtney', 'Day', 'courtney.day@sakilacustomer.org')
(246, 'Marian', 'Mendoza', 'marian.mendoza@sakilacustomer.org')
(247, 'Stella', 'Moreno', 'stella.moreno@sakilacustomer.org')
(248, 'Caroline', 'Bowman', 'caroline.bowman@sakilacustomer.org')
(249, 'Dora', 'Medina', 'dora.medina@sakilacustomer.org')
(250, 'Jo', 'Fowler', 'jo.fowler@sakilacustomer.org')
(251, 'Vickie', 'Brewer', 'vickie.brewer@sakilacustomer.org')
(252, 'Mattie', 'Hoffman', 'mattie.hoffman@sakilacustomer.org')
(253, 'Terry', 'Carlson', 'terry.carlson@sakilacustomer.org')
(254, 'Maxine', 'Silva', 'maxine.silva@sakilacustomer.org')
(255, 'Irma', 'Pearson', 'irma.pearson@sakilacustomer.org')
(256, 'Mabel', 'Holland', 'mabel.holland@sakilacustomer.org')
(257, 'Marsha', 'Douglas', 'marsha.douglas@sakilacustomer.org')
(258, 'Myrtle', 'Fleming', 'myrtle.fleming@sakilacustomer.org')
(259, 'Lena', 'Jensen', 'lena.jensen@sakilacustomer.org')
(260, 'Christy', 'Vargas', 'christy.vargas@sakilacustomer.org')
(261, 'Deanna', 'Byrd', 'deanna.byrd@sakilacustomer.org')
(262, 'Patsy', 'Davidson', 'patsy.davidson@sakilacustomer.org')
(263, 'Hilda', 'Hopkins', 'hilda.hopkins@sakilacustomer.org')
(264, 'Gwendolyn', 'May', 'gwendolyn.may@sakilacustomer.org')
(265, 'Jennie', 'Terry', 'jennie.terry@sakilacustomer.org')
(266, 'Nora', 'Herrera', 'nora.herrera@sakilacustomer.org')
(267, 'Margie', 'Wade', 'margie.wade@sakilacustomer.org')
(268, 'Nina', 'Soto', 'nina.soto@sakilacustomer.org')
(269, 'Cassandra', 'Walters', 'cassandra.walters@sakilacustomer.org')
(270, 'Leah', 'Curtis', 'leah.curtis@sakilacustomer.org')
(271, 'Penny', 'Neal', 'penny.neal@sakilacustomer.org')
(272, 'Kay', 'Caldwell', 'kay.caldwell@sakilacustomer.org')
(273, 'Priscilla', 'Lowe', 'priscilla.lowe@sakilacustomer.org')
(274, 'Naomi', 'Jennings', 'naomi.jennings@sakilacustomer.org')
(275, 'Carole', 'Barnett', 'carole.barnett@sakilacustomer.org')
(276, 'Brandy', 'Graves', 'brandy.graves@sakilacustomer.org')
(277, 'Olga', 'Jimenez', 'olga.jimenez@sakilacustomer.org')
(278, 'Billie', 'Horton', 'billie.horton@sakilacustomer.org')
(279, 'Dianne', 'Shelton', 'dianne.shelton@sakilacustomer.org')
(280, 'Tracey', 'Barrett', 'tracey.barrett@sakilacustomer.org')
(281, 'Leona', 'Obrien', 'leona.obrien@sakilacustomer.org')
(282, 'Jenny', 'Castro', 'jenny.castro@sakilacustomer.org')
(283, 'Felicia', 'Sutton', 'felicia.sutton@sakilacustomer.org')
(284, 'Sonia', 'Gregory', 'sonia.gregory@sakilacustomer.org')
(285, 'Miriam', 'Mckinney', 'miriam.mckinney@sakilacustomer.org')
(286, 'Velma', 'Lucas', 'velma.lucas@sakilacustomer.org')
(287, 'Becky', 'Miles', 'becky.miles@sakilacustomer.org')
(288, 'Bobbie', 'Craig', 'bobbie.craig@sakilacustomer.org')
(289, 'Violet', 'Rodriquez', 'violet.rodriquez@sakilacustomer.org')
(290, 'Kristina', 'Chambers', 'kristina.chambers@sakilacustomer.org')
(291, 'Toni', 'Holt', 'toni.holt@sakilacustomer.org')
(292, 'Misty', 'Lambert', 'misty.lambert@sakilacustomer.org')
(293, 'Mae', 'Fletcher', 'mae.fletcher@sakilacustomer.org')
(294, 'Shelly', 'Watts', 'shelly.watts@sakilacustomer.org')
(295, 'Daisy', 'Bates', 'daisy.bates@sakilacustomer.org')
(296, 'Ramona', 'Hale', 'ramona.hale@sakilacustomer.org')
(297, 'Sherri', 'Rhodes', 'sherri.rhodes@sakilacustomer.org')
(298, 'Erika', 'Pena', 'erika.pena@sakilacustomer.org')
(299, 'James', 'Gannon', 'james.gannon@sakilacustomer.org')
(300, 'John', 'Farnsworth', 'john.farnsworth@sakilacustomer.org')
(301, 'Robert', 'Baughman', 'robert.baughman@sakilacustomer.org')
(302, 'Michael', 'Silverman', 'michael.silverman@sakilacustomer.org')
(303, 'William', 'Satterfield', 'william.satterfield@sakilacustomer.org')
(304, 'David', 'Royal', 'david.royal@sakilacustomer.org')
(305, 'Richard', 'Mccrary', 'richard.mccrary@sakilacustomer.org')
(306, 'Charles', 'Kowalski', 'charles.kowalski@sakilacustomer.org')
(307, 'Joseph', 'Joy', 'joseph.joy@sakilacustomer.org')
(308, 'Thomas', 'Grigsby', 'thomas.grigsby@sakilacustomer.org')
(309, 'Christopher', 'Greco', 'christopher.greco@sakilacustomer.org')
(310, 'Daniel', 'Cabral', 'daniel.cabral@sakilacustomer.org')
(311, 'Paul', 'Trout', 'paul.trout@sakilacustomer.org')
(312, 'Mark', 'Rinehart', 'mark.rinehart@sakilacustomer.org')
(313, 'Donald', 'Mahon', 'donald.mahon@sakilacustomer.org')
(314, 'George', 'Linton', 'george.linton@sakilacustomer.org')
(315, 'Kenneth', 'Gooden', 'kenneth.gooden@sakilacustomer.org')
(316, 'Steven', 'Curley', 'steven.curley@sakilacustomer.org')
(317, 'Edward', 'Baugh', 'edward.baugh@sakilacustomer.org')
(318, 'Brian', 'Wyman', 'brian.wyman@sakilacustomer.org')
(319, 'Ronald', 'Weiner', 'ronald.weiner@sakilacustomer.org')
(320, 'Anthony', 'Schwab', 'anthony.schwab@sakilacustomer.org')
(321, 'Kevin', 'Schuler', 'kevin.schuler@sakilacustomer.org')
(322, 'Jason', 'Morrissey', 'jason.morrissey@sakilacustomer.org')
(323, 'Matthew', 'Mahan', 'matthew.mahan@sakilacustomer.org')
(324, 'Gary', 'Coy', 'gary.coy@sakilacustomer.org')

Попробуем параметризованный запрос

In [50]:
name = input("Введите имя клиента: ")

conn = psycopg.connect(conn_url)
cursor = conn.cursor()
cursor.execute(
    """
    SELECT
        customer_id,
        first_name,
        last_name,
        email
    FROM customer
    WHERE first_name = %s;
    """,
    (name,)
)

for row in cursor.fetchall():
    print(row)

cursor.close()
conn.close()

Введите имя клиента:  ' OR '1' = '1

**Несколько параметров**

In [51]:
min_len = 120
max_len = 130

conn = psycopg.connect(conn_url)
cursor = conn.cursor()
cursor.execute(
    """
    SELECT *
    FROM film
    WHERE length BETWEEN %s AND %s;
    """,
    (min_len, max_len)
)

for row in cursor.fetchall():
    print(row)

cursor.close()
conn.close()

(5, 'African Egg', 'A Fast-Paced Documentary of a Pastry Chef And a Dentist who must Pursue a Forensic Psychologist in The Gulf of Mexico', 2006, 1, 6, Decimal('2.99'), 130, Decimal('22.99'), 'G', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Deleted Scenes'], "'african':1 'chef':11 'dentist':14 'documentari':7 'egg':2 'fast':5 'fast-pac':4 'forens':19 'gulf':23 'mexico':25 'must':16 'pace':6 'pastri':10 'psychologist':20 'pursu':17")
(11, 'Alamo Videotape', 'A Boring Epistle of a Butler And a Cat who must Fight a Pastry Chef in A MySQL Convention', 2006, 1, 6, Decimal('0.99'), 126, Decimal('16.99'), 'G', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Commentaries', 'Behind the Scenes'], "'alamo':1 'bore':4 'butler':8 'cat':11 'chef':17 'convent':21 'epistl':5 'fight':14 'must':13 'mysql':20 'pastri':16 'videotap':2")
(21, 'American Circus', 'A Insightful Drama of a Girl And a Astronaut who must Face a Database Administrator in A Shark Tank', 2006, 1, 3, Decimal('4.99'), 129, Decimal('17.99'), 'R', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Commentaries', 'Behind the Scenes'], "'administr':17 'american':1 'astronaut':11 'circus':2 'databas':16 'drama':5 'face':14 'girl':8 'insight':4 'must':13 'shark':20 'tank':21")
(36, 'Argonauts Town', 'A Emotional Epistle of a Forensic Psychologist And a Butler who must Challenge a Waitress in An Abandoned Mine Shaft', 2006, 1, 7, Decimal('0.99'), 127, Decimal('12.99'), 'PG-13', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Trailers', 'Commentaries'], "'abandon':20 'argonaut':1 'butler':12 'challeng':15 'emot':4 'epistl':5 'forens':8 'mine':21 'must':14 'psychologist':9 'shaft':22 'town':2 'waitress':17")
(37, 'Arizona Bang', 'A Brilliant Panorama of a Mad Scientist And a Mad Cow who must Meet a Pioneer in A Monastery', 2006, 1, 3, Decimal('2.99'), 121, Decimal('28.99'), 'PG', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Trailers', 'Deleted Scenes'], "'arizona':1 'bang':2 'brilliant':4 'cow':13 'mad':8,12 'meet':16 'monasteri':21 'must':15 'panorama':5 'pioneer':18 'scientist':9")
(56, 'Barefoot Manchurian', 'A Intrepid Story of a Cat And a Student who must Vanquish a Girl in An Abandoned Amusement Park', 2006, 1, 6, Decimal('2.99'), 129, Decimal('15.99'), 'G', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Trailers', 'Commentaries'], "'abandon':19 'amus':20 'barefoot':1 'cat':8 'girl':16 'intrepid':4 'manchurian':2 'must':13 'park':21 'stori':5 'student':11 'vanquish':14")
(58, 'Beach Heartbreakers', 'A Fateful Display of a Womanizer And a Mad Scientist who must Outgun a A Shark in Soviet Georgia', 2006, 1, 6, Decimal('2.99'), 122, Decimal('16.99'), 'G', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Deleted Scenes', 'Behind the Scenes'], "'beach':1 'display':5 'fate':4 'georgia':21 'heartbreak':2 'mad':11 'must':14 'outgun':15 'scientist':12 'shark':18 'soviet':20 'woman':8")
(68, 'Betrayed Rear', 'A Emotional Character Study of a Boat And a Pioneer who must Find a Explorer in A Shark Tank', 2006, 1, 5, Decimal('4.99'), 122, Decimal('26.99'), 'NC-17', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Commentaries', 'Deleted Scenes', 'Behind the Scenes'], "'betray':1 'boat':9 'charact':5 'emot':4 'explor':17 'find':15 'must':14 'pioneer':12 'rear':2 'shark':20 'studi':6 'tank':21")
(86, 'Boogie Amelie', 'A Lacklusture Character Study of a Husband And a Sumo Wrestler who must Succumb a Technical Writer in The Gulf of Mexico', 2006, 1, 6, Decimal('4.99'), 121, Decimal('11.99'), 'R', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Commentaries', 'Behind the Scenes'], "'ameli':2 'boogi':1 'charact':5 'gulf':22 'husband':9 'lacklustur':4 'mexico':24 'must':15 'studi':6 'succumb':16 'sumo':12 'technic':18 'wrestler':13 'writer':19")
(93, 'Brannigan Sunrise', 'A Amazing Epistle of a Moose And a Crocodile who must Outrace a Dog in Berlin', 2006, 1, 4, Decimal('4.99'), 121, Decimal('27.99'), 'PG', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Trailers'], "'amaz':4 'berlin':18 'brannigan':1 'crocodil':11 'dog':16 'epistl':5 'moos':8 'must':13 'outrac':14 'sunris':2")
(95, 'Breakfast Goldfinger', 'A Beautiful Reflection of a Student And a Student who must Fight a Moose in Berlin', 2006, 1, 5, Decimal('4.99'), 123, Decimal('18.99'), 'G', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Trailers', 'Commentaries', 'Deleted Scenes'], "'beauti':4 'berlin':18 'breakfast':1 'fight':14 'goldfing':2 'moos':16 'must':13 'reflect':5 'student':8,11")
(105, 'Bull Shawshank', 'A Fanciful Drama of a Moose And a Squirrel who must Conquer a Pioneer in The Canadian Rockies', 2006, 1, 6, Decimal('0.99'), 125, Decimal('21.99'), 'NC-17', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Deleted Scenes'], "'bull':1 'canadian':19 'conquer':14 'drama':5 'fanci':4 'moos':8 'must':13 'pioneer':16 'rocki':20 'shawshank':2 'squirrel':11")
(112, 'Calendar Gunfight', 'A Thrilling Drama of a Frisbee And a Lumberjack who must Sink a Man in Nigeria', 2006, 1, 4, Decimal('4.99'), 120, Decimal('22.99'), 'NC-17', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Trailers', 'Commentaries', 'Behind the Scenes'], "'calendar':1 'drama':5 'frisbe':8 'gunfight':2 'lumberjack':11 'man':16 'must':13 'nigeria':18 'sink':14 'thrill':4")
(142, 'Chicken Hellfighters', 'A Emotional Drama of a Dog And a Explorer who must Outrace a Technical Writer in Australia', 2006, 1, 3, Decimal('0.99'), 122, Decimal('24.99'), 'PG', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Trailers', 'Commentaries', 'Deleted Scenes', 'Behind the Scenes'], "'australia':19 'chicken':1 'dog':8 'drama':5 'emot':4 'explor':11 'hellfight':2 'must':13 'outrac':14 'technic':16 'writer':17")
(145, 'Chisum Behavior', 'A Epic Documentary of a Sumo Wrestler And a Butler who must Kill a Car in Ancient India', 2006, 1, 5, Decimal('4.99'), 124, Decimal('25.99'), 'G', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Trailers', 'Commentaries', 'Behind the Scenes'], "'ancient':19 'behavior':2 'butler':12 'car':17 'chisum':1 'documentari':5 'epic':4 'india':20 'kill':15 'must':14 'sumo':8 'wrestler':9")
(158, 'Clones Pinocchio', 'A Amazing Drama of a Car And a Robot who must Pursue a Dentist in New Orleans', 2006, 1, 6, Decimal('2.99'), 124, Decimal('16.99'), 'R', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Behind the Scenes'], "'amaz':4 'car':8 'clone':1 'dentist':16 'drama':5 'must':13 'new':18 'orlean':19 'pinocchio':2 'pursu':14 'robot':11")
(170, 'Command Darling', 'A Awe-Inspiring Tale of a Forensic Psychologist And a Woman who must Challenge a Database Administrator in Ancient Japan', 2006, 1, 5, Decimal('4.99'), 120, Decimal('28.99'), 'PG-13', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Behind the Scenes'], "'administr':20 'ancient':22 'awe':5 'awe-inspir':4 'challeng':17 'command':1 'darl':2 'databas':19 'forens':10 'inspir':6 'japan':23 'must':16 'psychologist':11 'tale':7 'woman':14")
(175, 'Confused Candles', 'A Stunning Epistle of a Cat And a Forensic Psychologist who must Confront a Pioneer in A Baloon', 2006, 1, 3, Decimal('2.99'), 122, Decimal('27.99'), 'PG-13', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Trailers', 'Commentaries', 'Deleted Scenes', 'Behind the Scenes'], "'baloon':20 'candl':2 'cat':8 'confront':15 'confus':1 'epistl':5 'forens':11 'must':14 'pioneer':17 'psychologist':12 'stun':4")
(207, 'Dangerous Uptown', 'A Unbelieveable Story of a Mad Scientist And a Woman who must Overcome a Dog in California', 2006, 1, 7, Decimal('4.99'), 121, Decimal('26.99'), 'PG', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Commentaries'], "'california':19 'danger':1 'dog':17 'mad':8 'must':14 'overcom':15 'scientist':9 'stori':5 'unbeliev':4 'uptown':2 'woman':12")
(210, 'Darko Dorado', 'A Stunning Reflection of a Frisbee And a Husband who must Redeem a Dog in New Orleans', 2006, 1, 3, Decimal('4.99'), 130, Decimal('13.99'), 'NC-17', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Trailers', 'Commentaries', 'Deleted Scenes', 'Behind the Scenes'], "'darko':1 'dog':16 'dorado':2 'frisbe':8 'husband':11 'must':13 'new':18 'orlean':19 'redeem':14 'reflect':5 'stun':4")
(217, 'Dazed Punk', 'A Action-Packed Story of a Pioneer And a Technical Writer who must Discover a Forensic Psychologist in An Abandoned Amusement Park', 2006, 1, 6, Decimal('4.99'), 120, Decimal('20.99'), 'G', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Commentaries', 'Deleted Scenes'], "'abandon':23 'action':5 'action-pack':4 'amus':24 'daze':1 'discov':17 'forens':19 'must':16 'pack':6 'park':25 'pioneer':10 'psychologist':20 'punk':2 'stori':7 'technic':13 'writer':14")
(218, 'Deceiver Betrayed', 'A Taut Story of a Moose And a Squirrel who must Build a Husband in Ancient India', 2006, 1, 7, Decimal('0.99'), 122, Decimal('22.99'), 'NC-17', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Trailers', 'Commentaries', 'Deleted Scenes', 'Behind the Scenes'], "'ancient':18 'betray':2 'build':14 'deceiv':1 'husband':16 'india':19 'moos':8 'must':13 'squirrel':11 'stori':5 'taut':4")
(239, 'Dogma Family', 'A Brilliant Character Study of a Database Administrator And a Monkey who must Succumb a Astronaut in New Orleans', 2006, 1, 5, Decimal('4.99'), 122, Decimal('16.99'), 'G', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Commentaries'], "'administr':10 'astronaut':18 'brilliant':4 'charact':5 'databas':9 'dogma':1 'famili':2 'monkey':13 'must':15 'new':20 'orlean':21 'studi':6 'succumb':16")
(240, 'Dolls Rage', 'A Thrilling Display of a Pioneer And a Frisbee who must Escape a Teacher in The Outback', 2006, 1, 7, Decimal('2.99'), 120, Decimal('10.99'), 'PG-13', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Commentaries', 'Deleted Scenes'], "'display':5 'doll':1 'escap':14 'frisbe':11 'must':13 'outback':19 'pioneer':8 'rage':2 'teacher':16 'thrill':4")
(241, 'Donnie Alley', 'A Awe-Inspiring Tale of a Butler And a Frisbee who must Vanquish a Teacher in Ancient Japan', 2006, 1, 4, Decimal('0.99'), 125, Decimal('20.99'), 'NC-17', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Trailers', 'Commentaries', 'Behind the Scenes'], "'alley':2 'ancient':20 'awe':5 'awe-inspir':4 'butler':10 'donni':1 'frisbe':13 'inspir':6 'japan':21 'must':15 'tale':7 'teacher':18 'vanquish':16")
(277, 'Elephant Trojan', 'A Beautiful Panorama of a Lumberjack And a Forensic Psychologist who must Overcome a Frisbee in A Baloon', 2006, 1, 4, Decimal('4.99'), 126, Decimal('24.99'), 'PG-13', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Behind the Scenes'], "'baloon':20 'beauti':4 'eleph':1 'forens':11 'frisbe':17 'lumberjack':8 'must':14 'overcom':15 'panorama':5 'psychologist':12 'trojan':2")
(297, 'Extraordinary Conquerer', 'A Stunning Story of a Dog And a Feminist who must Face a Forensic Psychologist in Berlin', 2006, 1, 6, Decimal('2.99'), 122, Decimal('29.99'), 'G', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Trailers', 'Commentaries', 'Deleted Scenes'], "'berlin':19 'conquer':2 'dog':8 'extraordinari':1 'face':14 'feminist':11 'forens':16 'must':13 'psychologist':17 'stori':5 'stun':4")
(304, 'Fargo Gandhi', 'A Thrilling Reflection of a Pastry Chef And a Crocodile who must Reach a Teacher in The Outback', 2006, 1, 3, Decimal('2.99'), 130, Decimal('28.99'), 'G', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Deleted Scenes'], "'chef':9 'crocodil':12 'fargo':1 'gandhi':2 'must':14 'outback':20 'pastri':8 'reach':15 'reflect':5 'teacher':17 'thrill':4")
(319, 'Fish Opus', 'A Touching Display of a Feminist And a Girl who must Confront a Astronaut in Australia', 2006, 1, 4, Decimal('2.99'), 125, Decimal('22.99'), 'R', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Trailers', 'Deleted Scenes', 'Behind the Scenes'], "'astronaut':16 'australia':18 'confront':14 'display':5 'feminist':8 'fish':1 'girl':11 'must':13 'opus':2 'touch':4")
(321, 'Flash Wars', 'A Astounding Saga of a Moose And a Pastry Chef who must Chase a Student in The Gulf of Mexico', 2006, 1, 3, Decimal('4.99'), 123, Decimal('21.99'), 'NC-17', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Trailers', 'Commentaries', 'Behind the Scenes'], "'astound':4 'chase':15 'chef':12 'flash':1 'gulf':20 'mexico':22 'moos':8 'must':14 'pastri':11 'saga':5 'student':17 'war':2")
(333, 'Freaky Pocus', 'A Fast-Paced Documentary of a Pastry Chef And a Crocodile who must Chase a Squirrel in The Gulf of Mexico', 2006, 1, 7, Decimal('2.99'), 126, Decimal('16.99'), 'R', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Trailers', 'Behind the Scenes'], "'chase':17 'chef':11 'crocodil':14 'documentari':7 'fast':5 'fast-pac':4 'freaki':1 'gulf':22 'mexico':24 'must':16 'pace':6 'pastri':10 'pocus':2 'squirrel':19")
(346, 'Galaxy Sweethearts', 'A Emotional Reflection of a Womanizer And a Pioneer who must Face a Squirrel in Berlin', 2006, 1, 4, Decimal('4.99'), 128, Decimal('13.99'), 'R', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Deleted Scenes'], "'berlin':18 'emot':4 'face':14 'galaxi':1 'must':13 'pioneer':11 'reflect':5 'squirrel':16 'sweetheart':2 'woman':8")
(353, 'Gentlemen Stage', 'A Awe-Inspiring Reflection of a Monkey And a Student who must Overcome a Dentist in The First Manned Space Station', 2006, 1, 6, Decimal('2.99'), 125, Decimal('22.99'), 'NC-17', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Commentaries', 'Deleted Scenes'], "'awe':5 'awe-inspir':4 'dentist':18 'first':21 'gentlemen':1 'inspir':6 'man':22 'monkey':10 'must':15 'overcom':16 'reflect':7 'space':23 'stage':2 'station':24 'student':13")
(371, 'Gosford Donnie', 'A Epic Panorama of a Mad Scientist And a Monkey who must Redeem a Secret Agent in Berlin', 2006, 1, 5, Decimal('4.99'), 129, Decimal('17.99'), 'G', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Commentaries'], "'agent':18 'berlin':20 'donni':2 'epic':4 'gosford':1 'mad':8 'monkey':12 'must':14 'panorama':5 'redeem':15 'scientist':9 'secret':17")
(389, 'Gunfighter Mussolini', 'A Touching Saga of a Robot And a Boy who must Kill a Man in Ancient Japan', 2006, 1, 3, Decimal('2.99'), 127, Decimal('9.99'), 'PG-13', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Trailers', 'Commentaries'], "'ancient':18 'boy':11 'gunfight':1 'japan':19 'kill':14 'man':16 'mussolini':2 'must':13 'robot':8 'saga':5 'touch':4")
(403, 'Harry Idaho', 'A Taut Yarn of a Technical Writer And a Feminist who must Outrace a Dog in California', 2006, 1, 5, Decimal('4.99'), 121, Decimal('18.99'), 'PG-13', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Commentaries', 'Deleted Scenes'], "'california':19 'dog':17 'feminist':12 'harri':1 'idaho':2 'must':14 'outrac':15 'taut':4 'technic':8 'writer':9 'yarn':5")
(420, 'Holes Brannigan', 'A Fast-Paced Reflection of a Technical Writer And a Student who must Fight a Boy in The Canadian Rockies', 2006, 1, 7, Decimal('4.99'), 128, Decimal('27.99'), 'PG', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Commentaries', 'Behind the Scenes'], "'boy':19 'brannigan':2 'canadian':22 'fast':5 'fast-pac':4 'fight':17 'hole':1 'must':16 'pace':6 'reflect':7 'rocki':23 'student':14 'technic':10 'writer':11")
(436, 'Hours Rage', 'A Fateful Story of a Explorer And a Feminist who must Meet a Technical Writer in Soviet Georgia', 2006, 1, 4, Decimal('0.99'), 122, Decimal('14.99'), 'NC-17', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Trailers', 'Deleted Scenes'], "'explor':8 'fate':4 'feminist':11 'georgia':20 'hour':1 'meet':14 'must':13 'rage':2 'soviet':19 'stori':5 'technic':16 'writer':17")
(441, 'Hunter Alter', 'A Emotional Drama of a Mad Cow And a Boat who must Redeem a Secret Agent in A Shark Tank', 2006, 1, 5, Decimal('2.99'), 125, Decimal('21.99'), 'PG-13', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Commentaries', 'Deleted Scenes', 'Behind the Scenes'], "'agent':18 'alter':2 'boat':12 'cow':9 'drama':5 'emot':4 'hunter':1 'mad':8 'must':14 'redeem':15 'secret':17 'shark':21 'tank':22")
(452, 'Illusion Amelie', 'A Emotional Epistle of a Boat And a Mad Scientist who must Outrace a Robot in An Abandoned Mine Shaft', 2006, 1, 4, Decimal('0.99'), 122, Decimal('15.99'), 'R', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Commentaries', 'Behind the Scenes'], "'abandon':20 'ameli':2 'boat':8 'emot':4 'epistl':5 'illus':1 'mad':11 'mine':21 'must':14 'outrac':15 'robot':17 'scientist':12 'shaft':22")
(461, 'Insects Stone', 'A Epic Display of a Butler And a Dog who must Vanquish a Crocodile in A Manhattan Penthouse', 2006, 1, 3, Decimal('0.99'), 123, Decimal('14.99'), 'NC-17', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Trailers', 'Commentaries', 'Behind the Scenes'], "'butler':8 'crocodil':16 'display':5 'dog':11 'epic':4 'insect':1 'manhattan':19 'must':13 'penthous':20 'stone':2 'vanquish':14")
(476, 'Jason Trap', 'A Thoughtful Tale of a Woman And a A Shark who must Conquer a Dog in A Monastery', 2006, 1, 5, Decimal('2.99'), 130, Decimal('9.99'), 'NC-17', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Trailers', 'Deleted Scenes', 'Behind the Scenes'], "'conquer':15 'dog':17 'jason':1 'monasteri':20 'must':14 'shark':12 'tale':5 'thought':4 'trap':2 'woman':8")
(479, 'Jedi Beneath', 'A Astounding Reflection of a Explorer And a Dentist who must Pursue a Student in Nigeria', 2006, 1, 7, Decimal('0.99'), 128, Decimal('12.99'), 'PG', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Trailers', 'Commentaries', 'Deleted Scenes'], "'astound':4 'beneath':2 'dentist':11 'explor':8 'jedi':1 'must':13 'nigeria':18 'pursu':14 'reflect':5 'student':16")
(487, 'Jingle Sagebrush', 'A Epic Character Study of a Feminist And a Student who must Meet a Woman in A Baloon', 2006, 1, 6, Decimal('4.99'), 124, Decimal('29.99'), 'PG-13', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Trailers', 'Commentaries'], "'baloon':20 'charact':5 'epic':4 'feminist':9 'jingl':1 'meet':15 'must':14 'sagebrush':2 'student':12 'studi':6 'woman':17")
(490, 'Jumanji Blade', 'A Intrepid Yarn of a Husband And a Womanizer who must Pursue a Mad Scientist in New Orleans', 2006, 1, 4, Decimal('2.99'), 121, Decimal('13.99'), 'G', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Commentaries', 'Behind the Scenes'], "'blade':2 'husband':8 'intrepid':4 'jumanji':1 'mad':16 'must':13 'new':19 'orlean':20 'pursu':14 'scientist':17 'woman':11 'yarn':5")
(494, 'Karate Moon', 'A Astounding Yarn of a Womanizer And a Dog who must Reach a Waitress in A MySQL Convention', 2006, 1, 4, Decimal('0.99'), 120, Decimal('21.99'), 'PG-13', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Behind the Scenes'], "'astound':4 'convent':20 'dog':11 'karat':1 'moon':2 'must':13 'mysql':19 'reach':14 'waitress':16 'woman':8 'yarn':5")
(526, 'Lock Rear', 'A Thoughtful Character Study of a Squirrel And a Technical Writer who must Outrace a Student in Ancient Japan', 2006, 1, 7, Decimal('2.99'), 120, Decimal('10.99'), 'R', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Trailers', 'Commentaries'], "'ancient':20 'charact':5 'japan':21 'lock':1 'must':15 'outrac':16 'rear':2 'squirrel':9 'student':18 'studi':6 'technic':12 'thought':4 'writer':13")
(561, 'Mask Peach', 'A Boring Character Study of a Student And a Robot who must Meet a Woman in California', 2006, 1, 6, Decimal('2.99'), 123, Decimal('26.99'), 'NC-17', datetime.datetime(2013, 5, 26, 14, 50, 58, 951000), ['Commentaries', 'Deleted Scenes'], "'bore':4 'california':19 'charact':5 'mask':1 'meet':15 'must':14 'peach':2 'robot':12 'student':9 'studi':6 'woman':17")

# 3. Context manager

Правильный способ управления соединением

Если SQL содержит ошибку, произойдет exception и выполнение программы остановится

Код cursor.close() и conn.close() никогда не будет достигнут.

Это потенциально приводит к утечкам ресурсов

In [52]:
with psycopg.connect(conn_url) as conn:
    with conn.cursor() as cursor:
        cursor.execute("""
            SELECT *
            FROM customer
        """)
        rows = cursor.fetchall()

Внешний with управляет connection.

Внутренний with управляет cursor.

In [63]:
def execute_sql_script(query, conn_url):
    with psycopg.connect(conn_url) as conn:
        with conn.cursor() as cursor:
            cursor.execute(query)
            rows = cursor.fetchall()
    return rows

def build_dataframe(col_names, rows):
    df = pd.DataFrame(columns = list(col_names))
    for i, row in enumerate(rows):
        temp_df = pd.DataFrame(dict(zip(col_names, row)), index = [i])
        df = pd.concat([df, temp_df])
    return df

In [64]:
conn_url = f"postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
col_names = (
    "rental_id", 
    "inventory_id", 
    "customer_id", 
    "staff_id", 
    "film_id", 
    "rental_rate", 
    "length", 
    "replacement_cost", 
    "rating",
    "film_category",
    "fact_rental",
    "normative_rental",
    "is_overdue"
)

query = """
	SELECT 
		rental.rental_id,
		rental.inventory_id,
		rental.customer_id,
		rental.staff_id,
		film.film_id,
		film.rental_rate,
		film.length, 
		film.replacement_cost,
		film.rating, 
		category.name AS film_category,
		EXTRACT (EPOCH FROM rental.return_date - rental.rental_date)::FLOAT/86400 AS fact_rental,
		film.rental_duration AS normative_rental,
		CASE WHEN EXTRACT (EPOCH FROM rental.return_date - rental.rental_date)::FLOAT/86400 > film.rental_duration THEN 1 ELSE 0 END AS is_overdue
	FROM rental
	LEFT JOIN inventory 
	ON rental.inventory_id = inventory.inventory_id
	LEFT JOIN film 
	ON inventory.film_id = film.film_id
	LEFT JOIN film_category 
	ON film.film_id = film_category.film_id
	LEFT JOIN category
	ON film_category.category_id = category.category_id
	WHERE return_date IS NOT NULL
;
"""

In [67]:
rows = execute_sql_script(query, conn_url)
df = build_dataframe(col_names, rows[:100])

C:\Users\D\AppData\Local\Temp\ipykernel_11372\1101484450.py:12: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, temp_df])

In [69]:
df.head()

,rental_id,inventory_id,customer_id,staff_id,film_id,rental_rate,length,replacement_cost,rating,film_category,fact_rental,normative_rental,is_overdue
0,2,1525,459,1,333,2.99,126,16.99,R,Music,3.865278,7,0
1,3,1711,408,1,373,2.99,156,14.99,G,Children,7.964583,7,1
2,4,2452,333,2,535,0.99,181,21.99,R,Horror,9.110417,6,1
3,5,2079,222,1,450,2.99,84,29.99,NC-17,Children,8.227778,5,1
4,6,2792,549,1,613,0.99,92,19.99,NC-17,Comedy,2.100000,5,0

# 4. Sqlalchemy

In [70]:
from sqlalchemy import create_engine, text

In [81]:
engine = create_engine(conn_url)

with engine.connect() as conn:
    result = conn.execute(
        text("""
                SELECT *
                FROM customer
                WHERE customer_id = :cust_id
                OR customer_id = :cust_id
            """),
        {"cust_id": 15}
    )

    rows = result.fetchall()

In [82]:
rows

[(15, 1, 'Helen', 'Harris', 'helen.harris@sakilacustomer.org', 19, True, datetime.date(2006, 2, 14), datetime.datetime(2013, 5, 26, 14, 49, 45, 738000), 1),
 (16, 2, 'Sandra', 'Martin', 'sandra.martin@sakilacustomer.org', 20, True, datetime.date(2006, 2, 14), datetime.datetime(2013, 5, 26, 14, 49, 45, 738000), 0)]

In [74]:
result.keys()

RMKeyView(['customer_id', 'store_id', 'first_name', 'last_name', 'email', 'address_id', 'activebool', 'create_date', 'last_update', 'active'])

# 4. Psycopg + pandas

In [ ]:
import pandas as pd
import psycopg

In [89]:
conn_url = f"postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
conn = psycopg.connect(conn_url)

df = pd.read_sql(
    """
        SELECT *
        FROM customer;
    """,
    conn
)

conn.close()

C:\Users\D\AppData\Local\Temp\ipykernel_11372\901131811.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(

In [90]:
df.head()

,customer_id,store_id,first_name,last_name,email,address_id,activebool,create_date,last_update,active
0,524,1,Jared,Ely,jared.ely@sakilacustomer.org,530,True,2006-02-14,2013-05-26 14:49:45.738,1.0
1,1,1,Mary,Smith,mary.smith@sakilacustomer.org,5,True,2006-02-14,2013-05-26 14:49:45.738,1.0
2,2,1,Patricia,Johnson,patricia.johnson@sakilacustomer.org,6,True,2006-02-14,2013-05-26 14:49:45.738,1.0
3,3,1,Linda,Williams,linda.williams@sakilacustomer.org,7,True,2006-02-14,2013-05-26 14:49:45.738,1.0
4,4,2,Barbara,Jones,barbara.jones@sakilacustomer.org,8,True,2006-02-14,2013-05-26 14:49:45.738,1.0

# 5. SQLAlchemy + pandas

In [ ]:
from sqlalchemy import create_engine, text
import pandas as pd

In [91]:
engine = create_engine(conn_url)

df = pd.read_sql(text(
    """
        SELECT *
        FROM customer;
    """
    ),
    engine
)

Engine - это объект SQLAlchemy, который "знает", как подключаться к конкретной БД, управляет пулом соединений и предоставляет интерфейс для получения соединений и выполнения SQL

engine.dispose() закрывает соединение. Но он нужен, когда законичили использовать Engine

In [92]:
df.head()

,customer_id,store_id,first_name,last_name,email,address_id,activebool,create_date,last_update,active
0,524,1,Jared,Ely,jared.ely@sakilacustomer.org,530,True,2006-02-14,2013-05-26 14:49:45.738,1.0
1,1,1,Mary,Smith,mary.smith@sakilacustomer.org,5,True,2006-02-14,2013-05-26 14:49:45.738,1.0
2,2,1,Patricia,Johnson,patricia.johnson@sakilacustomer.org,6,True,2006-02-14,2013-05-26 14:49:45.738,1.0
3,3,1,Linda,Williams,linda.williams@sakilacustomer.org,7,True,2006-02-14,2013-05-26 14:49:45.738,1.0
4,4,2,Barbara,Jones,barbara.jones@sakilacustomer.org,8,True,2006-02-14,2013-05-26 14:49:45.738,1.0

In [93]:
df = pd.read_sql(text(
    """
        SELECT *
        FROM customer
        WHERE customer_id = :cust_id;
    """
    ),
    engine,
    params = {"cust_id" : 15}
)

In [94]:
df

,customer_id,store_id,first_name,last_name,email,address_id,activebool,create_date,last_update,active
0,15,1,Helen,Harris,helen.harris@sakilacustomer.org,19,True,2006-02-14,2013-05-26 14:49:45.738,1

**Чтение целой таблицы**

In [95]:
df_customers = pd.read_sql_table("customer", con = engine)

In [97]:
df_customers.head()

,customer_id,store_id,first_name,last_name,email,address_id,activebool,create_date,last_update,active
0,524,1,Jared,Ely,jared.ely@sakilacustomer.org,530,True,2006-02-14,2013-05-26 14:49:45.738,1.0
1,1,1,Mary,Smith,mary.smith@sakilacustomer.org,5,True,2006-02-14,2013-05-26 14:49:45.738,1.0
2,2,1,Patricia,Johnson,patricia.johnson@sakilacustomer.org,6,True,2006-02-14,2013-05-26 14:49:45.738,1.0
3,3,1,Linda,Williams,linda.williams@sakilacustomer.org,7,True,2006-02-14,2013-05-26 14:49:45.738,1.0
4,4,2,Barbara,Jones,barbara.jones@sakilacustomer.org,8,True,2006-02-14,2013-05-26 14:49:45.738,1.0

In [98]:
engine.dispose()

# 6. Правильное хранение паролей

Создаем файл .env в корневой папке каталога проекта

В этот файл размещаем текстом 
DB_HOST=localhost
DB_PORT=5432
DB_NAME=dvdrental
DB_USER=postgres
DB_PASSWORD=123

Добавлям .env в .gitignore

In [102]:
from dotenv import load_dotenv
import os

In [101]:
load_dotenv(r"C:\Users\D\Python scripts\Innopolis 2026\AI architecht\.env")

True

In [103]:
host = os.getenv("DB_HOST")
port = os.getenv("DB_PORT")
database = os.getenv("DB_NAME")
user = os.getenv("DB_USER")
password = os.getenv("DB_PASSWORD")

In [106]:
conn_url = f"postgresql://{user}:{password}@{host}:{port}/{database}"
engine = create_engine(conn_url)

df = pd.read_sql(text(
    """
        SELECT *
        FROM customer;
    """
    ),
    engine
)

In [107]:
df

,customer_id,store_id,first_name,last_name,email,address_id,activebool,create_date,last_update,active
0,524,1,Jared,Ely,jared.ely@sakilacustomer.org,530,True,2006-02-14,2013-05-26 14:49:45.738000,1.0
1,1,1,Mary,Smith,mary.smith@sakilacustomer.org,5,True,2006-02-14,2013-05-26 14:49:45.738000,1.0
2,2,1,Patricia,Johnson,patricia.johnson@sakilacustomer.org,6,True,2006-02-14,2013-05-26 14:49:45.738000,1.0
3,3,1,Linda,Williams,linda.williams@sakilacustomer.org,7,True,2006-02-14,2013-05-26 14:49:45.738000,1.0
4,4,2,Barbara,Jones,barbara.jones@sakilacustomer.org,8,True,2006-02-14,2013-05-26 14:49:45.738000,1.0
...,...,...,...,...,...,...,...,...,...,...
595,596,1,Enrique,Forsythe,enrique.forsythe@sakilacustomer.org,602,True,2006-02-14,2013-05-26 14:49:45.738000,1.0
596,597,1,Freddie,Duggan,freddie.duggan@sakilacustomer.org,603,True,2006-02-14,2013-05-26 14:49:45.738000,1.0
597,598,1,Wade,Delvalle,wade.delvalle@sakilacustomer.org,604,True,2006-02-14,2013-05-26 14:49:45.738000,1.0
598,599,2,Austin,Cintron,austin.cintron@sakilacustomer.org,605,True,2006-02-14,2013-05-26 14:49:45.738000,1.0
599,609,1,Петр,Николаев,petr.nikolaev@example.ru,5,True,2026-08-07,2026-08-07 21:53:07.843764,NaN